
import mongoose from "mongoose";

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      unique: true,
      // Will be auto-generated by pre-save hook
    },
    client: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Client",
      required: true,
    },
    subscription: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subscription",
    },
    payment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Payment",
    },
    company: {
      type: String,
      required: true,
      enum: ["We Alll", "Kolkata Digital"],
    },
    companyDetails: {
      name: String,
      address: String,
      phone: Number,
      email: String,
      gstin: String,
      stateCode: String,
      stateName: String,
      logo: String,
      bankDetails: {
        accountHolderName: String,
        bankName: String,
        accountNumber: String,
        ifscCode: String,
        branch: String,
      },
    },
    clientDetails: {
      name: String,
      email: String,
      phone: Number,
      address: String,
      gstin: String,
      stateCode: String,
      stateName: String,
    },
    referenceNumber: String,
    otherReferences: String,
    buyerOrderNumber: String,
    planDetails: {
      name: String,
      description: String,
      amount: Number,
      hsnSac: String,
    },
    addOns: [
      {
        addOn: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "AddOn",
        },
        name: String,
        description: String,
        quantity: {
          type: Number,
          default: 1,
        },
        unitPrice: Number,
        amount: Number,
        hsnSac: String,
      },
    ],
    customItems: [
      {
        description: String,
        quantity: {
          type: Number,
          default: 1,
        },
        unitPrice: Number,
        amount: Number,
        hsnSac: String,
      },
    ],
    subtotal: {
      type: Number,
      required: true,
    },
    cgstRate: {
      type: Number,
      default: 9,
    },
    cgstAmount: {
      type: Number,
      default: 0,
    },
    sgstRate: {
      type: Number,
      default: 9,
    },
    sgstAmount: {
      type: Number,
      default: 0,
    },
    totalTax: {
      type: Number,
      required: true,
    },
    discount: {
      type: Number,
      default: 0,
    },
    discountReason: {
      type: String,
    },
    totalAmount: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      enum: ["draft", "sent", "paid", "overdue", "cancelled"],
      default: "draft",
    },
    issueDate: {
      type: Date,
      required: true,
      default: Date.now,
    },
    dueDate: {
      type: Date,
      required: true,
    },
    paidDate: {
      type: Date,
    },
    notes: {
      type: String,
    },
    termsAndConditions: {
      type: String,
    },
    pdfPath: {
      type: String,
    },
    sentAt: {
      type: Date,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  { timestamps: true }
);

// Auto-generate invoice number
invoiceSchema.pre("save", async function (next) {
  if (this.isNew && !this.invoiceNumber) {
    const year = new Date().getFullYear();
    const count = await mongoose.model("Invoice").countDocuments();
    this.invoiceNumber = `INV-${year}-${String(count + 1).padStart(4, "0")}`;
  }
  next();
});

// Indexes for faster queries
invoiceSchema.index({ client: 1 });
invoiceSchema.index({ status: 1 });
invoiceSchema.index({ company: 1 });
invoiceSchema.index({ issueDate: -1 });

const Invoice = mongoose.model("Invoice", invoiceSchema);
export default Invoice;
