import mongoose from "mongoose";

const subscriptionSchema = new mongoose.Schema(
  {
    subscriptionNumber: {
      type: String,
      unique: true,
      // Will be auto-generated by pre-save hook
    },
    client: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Client",
      required: true,
    },
    plan: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Plan",
      required: true,
    },
    planSnapshot: {
      name: String,
      price: Number,
      billingCycle: String,
      features: [String],
    },
    addOns: [
      {
        addOn: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "AddOn",
        },
        name: String,
        price: Number,
        billingType: String,
      },
    ],
    company: {
      type: String,
      required: true,
      enum: ["We Alll", "Kolkata Digital"],
    },
    status: {
      type: String,
      enum: ["pending", "active", "cancelled", "expired", "suspended"],
      default: "pending",
    },
    billingCycle: {
      type: String,
      required: true,
      enum: ["monthly", "quarterly", "half-yearly", "yearly", "one-time"],
    },
    startDate: {
      type: Date,
    },
    endDate: {
      type: Date,
    },
    nextBillingDate: {
      type: Date,
    },
    autoRenew: {
      type: Boolean,
      default: false,
    },
    planAmount: {
      type: Number,
      default: 0,
    },
    addOnsAmount: {
      type: Number,
      default: 0,
    },
    subtotal: {
      type: Number,
      default: 0,
    },
    taxPercentage: {
      type: Number,
      default: 18, // GST will be seperated with 9 % CGST and 9 % SGST
    },
    taxAmount: {
      type: Number,
      default: 0,
    },
    totalAmount: {
      type: Number,
      default: 0,
    },
    discount: {
      type: Number,
      default: 0,
    },
    discountReason: {
      type: String,
    },
    notes: {
      type: String,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    activatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    activatedAt: {
      type: Date,
    },
    cancelledBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    cancelledAt: {
      type: Date,
    },
    cancellationReason: {
      type: String,
    },
  },
  { timestamps: true }
);

// Auto-generate subscription number
subscriptionSchema.pre("save", async function (next) {
  if (this.isNew && !this.subscriptionNumber) {
    const year = new Date().getFullYear();
    const count = await mongoose.model("Subscription").countDocuments();
    this.subscriptionNumber = `SUB-${year}-${String(count + 1).padStart(
      4,
      "0"
    )}`;
  }
  next();
});

// Indexes for faster queries
subscriptionSchema.index({ client: 1, status: 1 });
subscriptionSchema.index({ company: 1 });
subscriptionSchema.index({ status: 1 });
subscriptionSchema.index({ nextBillingDate: 1 });

const Subscription = mongoose.model("Subscription", subscriptionSchema);
export default Subscription;
