import mongoose from "mongoose";

const workCalendarSchema = new mongoose.Schema(
  {
    // Core Work Information
    title: {
      type: String,
      required: [true, "Work title is required"],
      trim: true,
    },
    description: {
      type: String,
      trim: true,
    },
    
    // Work Type and Category
    workType: {
      type: String,
      enum: [
        "work-item",
        "project-milestone", 
        "meeting",
        "deadline",
        "review",
        "presentation",
        "training",
        "client-call",
        "internal-task",
        "other"
      ],
      required: true,
      index: true,
    },
    
    // References to source entities
    sourceId: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: "sourceModel",
    },
    sourceModel: {
      type: String,
      enum: ["WorkItem", "Project", "CalendarEvent", "User"],
    },
    
    // Employee Assignment
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    
    // Department and Project Context
    department: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Department",
      required: true,
      index: true,
    },
    project: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
      index: true,
    },
    client: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Client",
      index: true,
    },
    
    // Date and Time Information
    startDate: {
      type: Date,
      required: true,
      index: true,
    },
    endDate: {
      type: Date,
      required: true,
      index: true,
    },
    dueDate: {
      type: Date,
      index: true,
    },
    isAllDay: {
      type: Boolean,
      default: false,
    },
    
    // Status and Progress
    status: {
      type: String,
      enum: ["scheduled", "in-progress", "completed", "cancelled", "postponed", "overdue"],
      default: "scheduled",
      index: true,
    },
    priority: {
      type: String,
      enum: ["low", "medium", "high", "urgent"],
      default: "medium",
      index: true,
    },
    progress: {
      type: Number,
      min: 0,
      max: 100,
      default: 0,
    },
    
    // Workflow Context
    workflowStage: {
      type: String,
      index: true,
    },
    workflowType: {
      type: String,
      index: true,
    },
    
    // Time Tracking
    timeTracking: {
      estimatedHours: {
        type: Number,
        default: 0,
      },
      actualHours: {
        type: Number,
        default: 0,
      },
      startedAt: Date,
      completedAt: Date,
      breaks: [{
        startTime: Date,
        endTime: Date,
        reason: String,
      }],
    },
    
    // Location and Resources
    location: {
      type: String,
      trim: true,
    },
    isRemote: {
      type: Boolean,
      default: false,
    },
    meetingUrl: String,
    
    // Deliverables and Attachments
    deliverables: [{
      name: String,
      description: String,
      url: String,
      type: {
        type: String,
        enum: ["document", "image", "video", "code", "design", "other"],
      },
      status: {
        type: String,
        enum: ["pending", "in-progress", "completed", "approved", "rejected"],
        default: "pending",
      },
      submittedAt: Date,
      approvedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      approvedAt: Date,
    }],
    
    // Comments and Notes
    notes: [{
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      text: String,
      type: {
        type: String,
        enum: ["note", "update", "issue", "solution"],
        default: "note",
      },
      createdAt: {
        type: Date,
        default: Date.now,
      },
    }],
    
    // Performance Metrics
    metrics: {
      qualityScore: {
        type: Number,
        min: 0,
        max: 10,
      },
      clientSatisfaction: {
        type: Number,
        min: 0,
        max: 10,
      },
      onTimeDelivery: {
        type: Boolean,
        default: true,
      },
      budgetCompliance: {
        type: Number, // Percentage
        min: 0,
        max: 200,
      },
    },
    
    // Collaboration
    collaborators: [{
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
      role: String,
      contribution: {
        type: Number,
        min: 0,
        max: 100,
      },
    }],
    
    // Visibility and Access
    visibility: {
      type: String,
      enum: ["public", "department", "project", "private"],
      default: "project",
    },
    
    // Auto-generation flags
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    autoGeneratedBy: String,
    
    // Tracking and Audit
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    lastModifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    
    // Tags for advanced filtering
    tags: [{
      type: String,
      trim: true,
      lowercase: true,
    }],
    
    // Custom fields for department-specific data
    customFields: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Indexes for optimal performance
workCalendarSchema.index({ assignedTo: 1, startDate: 1 });
workCalendarSchema.index({ department: 1, startDate: 1 });
workCalendarSchema.index({ project: 1, startDate: 1 });
workCalendarSchema.index({ client: 1, startDate: 1 });
workCalendarSchema.index({ status: 1, priority: 1 });
workCalendarSchema.index({ workType: 1, workflowStage: 1 });
workCalendarSchema.index({ dueDate: 1, status: 1 });
workCalendarSchema.index({ createdAt: 1 });

// Compound indexes for complex queries
workCalendarSchema.index({ department: 1, assignedTo: 1, startDate: 1 });
workCalendarSchema.index({ project: 1, status: 1, startDate: 1 });
workCalendarSchema.index({ client: 1, department: 1, startDate: 1 });

// Virtual for duration in hours
workCalendarSchema.virtual("durationHours").get(function () {
  if (this.startDate && this.endDate) {
    return Math.round((this.endDate - this.startDate) / (1000 * 60 * 60) * 100) / 100;
  }
  return 0;
});

// Virtual for checking if work is overdue
workCalendarSchema.virtual("isOverdue").get(function () {
  if (this.status === "completed" || this.status === "cancelled") {
    return false;
  }
  const checkDate = this.dueDate || this.endDate;
  return checkDate && new Date() > checkDate;
});

// Virtual for efficiency score
workCalendarSchema.virtual("efficiencyScore").get(function () {
  if (!this.timeTracking.estimatedHours || !this.timeTracking.actualHours) {
    return null;
  }
  return Math.round((this.timeTracking.estimatedHours / this.timeTracking.actualHours) * 100);
});

// Pre-save middleware to update status based on dates
workCalendarSchema.pre("save", function (next) {
  const now = new Date();
  
  // Auto-update status based on dates
  if (this.status === "scheduled" && this.startDate <= now) {
    this.status = "in-progress";
  }
  
  if (this.status === "in-progress" && this.isOverdue) {
    this.status = "overdue";
  }
  
  // Set completion time
  if (this.status === "completed" && !this.timeTracking.completedAt) {
    this.timeTracking.completedAt = now;
  }
  
  next();
});

// Static method to get work calendar for employee
workCalendarSchema.statics.getEmployeeCalendar = function (employeeId, filters = {}) {
  const query = { assignedTo: employeeId };
  
  // Apply date range filter
  if (filters.startDate && filters.endDate) {
    query.$or = [
      {
        startDate: { $gte: new Date(filters.startDate), $lte: new Date(filters.endDate) },
      },
      {
        endDate: { $gte: new Date(filters.startDate), $lte: new Date(filters.endDate) },
      },
    ];
  }
  
  // Apply other filters
  if (filters.status) query.status = filters.status;
  if (filters.workType) query.workType = filters.workType;
  if (filters.project) query.project = filters.project;
  if (filters.priority) query.priority = filters.priority;
  
  return this.find(query)
    .populate("project", "name client")
    .populate("client", "name")
    .populate("department", "name")
    .populate("assignedTo", "name email")
    .populate("collaborators.user", "name email")
    .sort({ startDate: 1 });
};

// Static method to get admin overview
workCalendarSchema.statics.getAdminOverview = function (filters = {}) {
  const query = {};
  
  // Apply filters
  if (filters.department) query.department = filters.department;
  if (filters.project) query.project = filters.project;
  if (filters.client) query.client = filters.client;
  if (filters.assignedTo) query.assignedTo = filters.assignedTo;
  if (filters.status) query.status = filters.status;
  if (filters.workType) query.workType = filters.workType;
  
  // Date range filter
  if (filters.startDate && filters.endDate) {
    query.startDate = { 
      $gte: new Date(filters.startDate), 
      $lte: new Date(filters.endDate) 
    };
  }
  
  return this.find(query)
    .populate("assignedTo", "name email role")
    .populate("department", "name")
    .populate("project", "name client status")
    .populate("client", "name email")
    .populate("createdBy", "name email")
    .sort({ startDate: 1 });
};

// Static method to get analytics data
workCalendarSchema.statics.getAnalytics = function (filters = {}) {
  const pipeline = [
    {
      $match: filters,
    },
    {
      $group: {
        _id: null,
        totalWork: { $sum: 1 },
        completedWork: {
          $sum: { $cond: [{ $eq: ["$status", "completed"] }, 1, 0] },
        },
        overdueWork: {
          $sum: { $cond: [{ $eq: ["$status", "overdue"] }, 1, 0] },
        },
        totalHours: { $sum: "$timeTracking.actualHours" },
        avgEfficiency: { $avg: "$efficiencyScore" },
        avgQuality: { $avg: "$metrics.qualityScore" },
      },
    },
  ];
  
  return this.aggregate(pipeline);
};

const WorkCalendar = mongoose.model("WorkCalendar", workCalendarSchema);

export default WorkCalendar;