/**
 * Authorization V2 — Maps legacy User.role to Access Role grants.
 * HoD users receive employee_standard + department_head grants (union).
 */

import { SCOPES } from './scopes.js';

/** @typedef {{ accessRole: string, grants: import('./scopes.js').PermissionGrant[] }} AccessRoleDefinition */

const EMPLOYEE_STANDARD_GRANTS = [
  { permission: 'dashboard.view', scope: SCOPES.SELF },
  { permission: 'profile.view', scope: SCOPES.SELF },
  { permission: 'profile.update', scope: SCOPES.SELF },
  { permission: 'support.view', scope: SCOPES.COMPANY },
  { permission: 'attendance.record.view_self', scope: SCOPES.SELF },
  { permission: 'attendance.clock', scope: SCOPES.SELF },
  { permission: 'leave.request.create', scope: SCOPES.SELF },
  { permission: 'leave.request.view_self', scope: SCOPES.SELF },
  { permission: 'worklog.entry.create', scope: SCOPES.SELF },
  { permission: 'worklog.entry.view_self', scope: SCOPES.SELF },
  { permission: 'projects.project.view', scope: SCOPES.PROJECT },
  { permission: 'crm.client.view_assigned', scope: SCOPES.PROJECT },
  { permission: 'work.item.view', scope: SCOPES.PROJECT },
  { permission: 'work.item.create', scope: SCOPES.SELF },
  { permission: 'work.item.update', scope: SCOPES.SELF },
  { permission: 'company.meeting.view', scope: SCOPES.COMPANY },
  { permission: 'company.policy.view', scope: SCOPES.COMPANY },
  { permission: 'company.announcement.view', scope: SCOPES.COMPANY },
  { permission: 'team.department.view', scope: SCOPES.COMPANY },
  { permission: 'procurement.pr.create', scope: SCOPES.SELF },
  { permission: 'procurement.pr.view_self', scope: SCOPES.SELF },
  { permission: 'expense.claim.create', scope: SCOPES.SELF },
  { permission: 'payroll.slip.view_self', scope: SCOPES.SELF },
  { permission: 'assets.asset.view', scope: SCOPES.SELF },
  { permission: 'licenses.license.view', scope: SCOPES.SELF },
];

const DEPARTMENT_HEAD_GRANTS = [
  { permission: 'attendance.record.view', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'leave.request.view', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'leave.request.approve', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'worklog.entry.review', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'hiring.request.create', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'hiring.request.view', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'procurement.pr.approve_hod', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'procurement.pr.view', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'work.item.approve', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'projects.project.manage', scope: SCOPES.OWN_DEPARTMENT },
  { permission: 'reports.analytics.view', scope: SCOPES.OWN_DEPARTMENT },
];

/** @type {Record<string, AccessRoleDefinition[]>} */
export const LEGACY_ROLE_TO_ACCESS_ROLES = {
  superadmin: [
    {
      accessRole: 'platform_super_admin',
      grants: [{ permission: 'platform.admin', scope: SCOPES.PLATFORM }],
    },
  ],
  admin: [
    {
      accessRole: 'company_admin',
      grants: [
        { permission: 'dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.create', scope: SCOPES.COMPANY },
        { permission: 'team.user.update', scope: SCOPES.COMPANY },
        { permission: 'team.department.view', scope: SCOPES.COMPANY },
        { permission: 'team.department.manage', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.view', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.manage', scope: SCOPES.COMPANY },
        { permission: 'attendance.clock', scope: SCOPES.SELF },
        { permission: 'attendance.record.view_self', scope: SCOPES.SELF },
        { permission: 'leave.request.view', scope: SCOPES.COMPANY },
        { permission: 'leave.request.approve', scope: SCOPES.COMPANY },
        { permission: 'leave.request.create', scope: SCOPES.SELF },
        { permission: 'leave.request.view_self', scope: SCOPES.SELF },
        { permission: 'worklog.entry.review', scope: SCOPES.COMPANY },
        { permission: 'worklog.entry.create', scope: SCOPES.SELF },
        { permission: 'worklog.entry.view_self', scope: SCOPES.SELF },
        { permission: 'projects.project.view', scope: SCOPES.COMPANY },
        { permission: 'projects.project.manage', scope: SCOPES.COMPANY },
        { permission: 'work.item.view', scope: SCOPES.COMPANY },
        { permission: 'work.item.create', scope: SCOPES.COMPANY },
        { permission: 'work.item.update', scope: SCOPES.COMPANY },
        { permission: 'work.item.approve', scope: SCOPES.COMPANY },
        { permission: 'work.dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'company.meeting.manage', scope: SCOPES.COMPANY },
        { permission: 'company.policy.view', scope: SCOPES.COMPANY },
        { permission: 'company.policy.manage', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.view', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.manage', scope: SCOPES.COMPANY },
        { permission: 'hiring.pipeline.manage', scope: SCOPES.COMPANY },
        { permission: 'hiring.request.view', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.approve_admin', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.approve_hod', scope: SCOPES.COMPANY },
        { permission: 'procurement.po.manage', scope: SCOPES.COMPANY },
        { permission: 'procurement.vendor.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.lead.view', scope: SCOPES.COMPANY },
        { permission: 'crm.lead.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.client.view', scope: SCOPES.COMPANY },
        { permission: 'crm.client.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.rawdata.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.create', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.view_self', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.view', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.view', scope: SCOPES.COMPANY },
        { permission: 'billing.payment.verify', scope: SCOPES.COMPANY },
        { permission: 'expense.claim.approve', scope: SCOPES.COMPANY },
        { permission: 'payroll.structure.manage', scope: SCOPES.COMPANY },
        { permission: 'payroll.slip.manage', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.view', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.manage', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.view', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.manage', scope: SCOPES.COMPANY },
        { permission: 'reports.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'support.view', scope: SCOPES.COMPANY },
        { permission: 'support.manage', scope: SCOPES.COMPANY },
        { permission: 'profile.view', scope: SCOPES.SELF },
        { permission: 'profile.update', scope: SCOPES.SELF },
        { permission: 'auth.role.manage', scope: SCOPES.COMPANY },
        { permission: 'auth.permission.assign', scope: SCOPES.COMPANY },
      ],
    },
  ],
  hr: [
    {
      accessRole: 'hr_manager',
      grants: [
        { permission: 'dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.create', scope: SCOPES.COMPANY },
        { permission: 'team.user.update', scope: SCOPES.COMPANY },
        { permission: 'team.department.view', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.view', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.manage', scope: SCOPES.COMPANY },
        { permission: 'attendance.clock', scope: SCOPES.SELF },
        { permission: 'leave.request.view', scope: SCOPES.COMPANY },
        { permission: 'leave.request.approve', scope: SCOPES.COMPANY },
        { permission: 'worklog.entry.review', scope: SCOPES.COMPANY },
        { permission: 'work.item.view', scope: SCOPES.COMPANY },
        { permission: 'work.item.create', scope: SCOPES.COMPANY },
        { permission: 'work.item.update', scope: SCOPES.COMPANY },
        { permission: 'work.item.approve', scope: SCOPES.COMPANY },
        { permission: 'work.dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.view', scope: SCOPES.COMPANY },
        { permission: 'hiring.pipeline.manage', scope: SCOPES.COMPANY },
        { permission: 'hiring.request.view', scope: SCOPES.COMPANY },
        { permission: 'payroll.structure.manage', scope: SCOPES.COMPANY },
        { permission: 'payroll.slip.manage', scope: SCOPES.COMPANY },
        { permission: 'projects.project.view', scope: SCOPES.COMPANY },
        { permission: 'projects.project.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.client.view', scope: SCOPES.COMPANY },
        { permission: 'crm.client.manage', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.view', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.manage', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.view', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.manage', scope: SCOPES.COMPANY },
        { permission: 'company.policy.manage', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.manage', scope: SCOPES.COMPANY },
        { permission: 'company.meeting.manage', scope: SCOPES.COMPANY },
        { permission: 'expense.claim.approve', scope: SCOPES.COMPANY },
        { permission: 'reports.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'profile.view', scope: SCOPES.SELF },
        { permission: 'profile.update', scope: SCOPES.SELF },
        ...EMPLOYEE_STANDARD_GRANTS.filter(
          (g) => !['profile.view', 'profile.update', 'dashboard.view'].includes(g.permission)
        ),
      ],
    },
  ],
  accounts: [
    {
      accessRole: 'finance_accounts',
      grants: [
        { permission: 'dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.view', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.payment.verify', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.approve_admin', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.approve_hod', scope: SCOPES.COMPANY },
        { permission: 'procurement.po.manage', scope: SCOPES.COMPANY },
        { permission: 'procurement.vendor.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.lead.view', scope: SCOPES.COMPANY },
        { permission: 'crm.client.view', scope: SCOPES.COMPANY },
        { permission: 'crm.client.manage', scope: SCOPES.COMPANY },
        { permission: 'payroll.slip.manage', scope: SCOPES.COMPANY },
        { permission: 'payroll.structure.manage', scope: SCOPES.COMPANY },
        { permission: 'expense.claim.approve', scope: SCOPES.COMPANY },
        { permission: 'reports.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'support.view', scope: SCOPES.COMPANY },
        { permission: 'company.meeting.view', scope: SCOPES.COMPANY },
        { permission: 'company.policy.view', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.view', scope: SCOPES.COMPANY },
        { permission: 'profile.view', scope: SCOPES.SELF },
        { permission: 'profile.update', scope: SCOPES.SELF },
      ],
    },
  ],
  manager: [
    {
      accessRole: 'operations_manager',
      grants: [
        { permission: 'dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.view', scope: SCOPES.COMPANY },
        { permission: 'team.user.create', scope: SCOPES.COMPANY },
        { permission: 'team.user.update', scope: SCOPES.COMPANY },
        { permission: 'team.department.view', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.view', scope: SCOPES.COMPANY },
        { permission: 'attendance.record.manage', scope: SCOPES.COMPANY },
        { permission: 'leave.request.view', scope: SCOPES.COMPANY },
        { permission: 'leave.request.approve', scope: SCOPES.COMPANY },
        { permission: 'worklog.entry.review', scope: SCOPES.COMPANY },
        { permission: 'projects.project.view', scope: SCOPES.COMPANY },
        { permission: 'projects.project.manage', scope: SCOPES.COMPANY },
        { permission: 'work.item.view', scope: SCOPES.COMPANY },
        { permission: 'work.dashboard.view', scope: SCOPES.COMPANY },
        { permission: 'crm.lead.view', scope: SCOPES.COMPANY },
        { permission: 'crm.lead.manage', scope: SCOPES.COMPANY },
        { permission: 'crm.client.view', scope: SCOPES.COMPANY },
        { permission: 'procurement.pr.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.view', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.payment.verify', scope: SCOPES.COMPANY },
        { permission: 'expense.claim.approve', scope: SCOPES.COMPANY },
        { permission: 'payroll.structure.manage', scope: SCOPES.COMPANY },
        { permission: 'payroll.slip.manage', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.view', scope: SCOPES.COMPANY },
        { permission: 'assets.asset.manage', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.view', scope: SCOPES.COMPANY },
        { permission: 'licenses.license.manage', scope: SCOPES.COMPANY },
        { permission: 'reports.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'crm.rawdata.analytics.view', scope: SCOPES.COMPANY },
        { permission: 'company.policy.manage', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.manage', scope: SCOPES.COMPANY },
        { permission: 'company.meeting.manage', scope: SCOPES.COMPANY },
        { permission: 'hiring.pipeline.manage', scope: SCOPES.COMPANY },
        { permission: 'hiring.request.view', scope: SCOPES.COMPANY },
        { permission: 'profile.view', scope: SCOPES.SELF },
        { permission: 'profile.update', scope: SCOPES.SELF },
        ...EMPLOYEE_STANDARD_GRANTS.filter(
          (g) => !['profile.view', 'profile.update', 'dashboard.view'].includes(g.permission)
        ),
      ],
    },
  ],
  employee: [
    {
      accessRole: 'employee_standard',
      grants: EMPLOYEE_STANDARD_GRANTS,
    },
  ],
  hod: [
    {
      accessRole: 'employee_standard',
      grants: [
        ...EMPLOYEE_STANDARD_GRANTS,
        { permission: 'billing.invoice.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.manage', scope: SCOPES.COMPANY },
        { permission: 'billing.subscription.view', scope: SCOPES.COMPANY },
      ],
    },
    {
      accessRole: 'department_head',
      grants: DEPARTMENT_HEAD_GRANTS,
    },
  ],
  sales: [
    {
      accessRole: 'employee_standard',
      grants: EMPLOYEE_STANDARD_GRANTS,
    },
    {
      accessRole: 'sales_rep',
      grants: [
        { permission: 'crm.lead.view', scope: SCOPES.ASSIGNED_DEPARTMENTS },
        { permission: 'crm.lead.manage', scope: SCOPES.ASSIGNED_DEPARTMENTS },
        { permission: 'crm.client.view', scope: SCOPES.ASSIGNED_DEPARTMENTS },
        { permission: 'crm.rawdata.manage', scope: SCOPES.ASSIGNED_DEPARTMENTS },
      ],
    },
  ],
  client: [
    {
      accessRole: 'external_client',
      grants: [
        { permission: 'dashboard.view', scope: SCOPES.SELF },
        { permission: 'profile.view', scope: SCOPES.SELF },
        { permission: 'profile.update', scope: SCOPES.SELF },
        { permission: 'support.view', scope: SCOPES.COMPANY },
        { permission: 'company.meeting.view', scope: SCOPES.COMPANY },
        { permission: 'company.policy.view', scope: SCOPES.COMPANY },
        { permission: 'company.announcement.view', scope: SCOPES.COMPANY },
        { permission: 'billing.invoice.view', scope: SCOPES.CLIENT_PORTFOLIO },
        { permission: 'billing.subscription.view', scope: SCOPES.CLIENT_PORTFOLIO },
        { permission: 'billing.subscription.manage', scope: SCOPES.CLIENT_PORTFOLIO },
        { permission: 'projects.project.view', scope: SCOPES.CLIENT_PORTFOLIO },
      ],
    },
  ],
};

/**
 * Superadmin receives all catalog permissions at PLATFORM scope (implicit via platform.admin).
 * For effective API we expand platform.admin to all keys in adapter.
 */

export const ALL_LEGACY_ROLES = Object.keys(LEGACY_ROLE_TO_ACCESS_ROLES);
