/**
 * Enhanced Work Calendar Property-Based Tests
 * Tests for advanced filtering, client focus, and bulk operations
 */

import mongoose from 'mongoose';

// Mock data generators for property-based testing
const generateClient = () => ({
  _id: new mongoose.Types.ObjectId(),
  name: `Client ${Math.random().toString(36).substr(2, 9)}`,
  email: `client${Math.random().toString(36).substr(2, 5)}@example.com`,
  company: `Company ${Math.random().toString(36).substr(2, 7)}`,
  status: 'active'
});

const generateProject = (clientId) => ({
  _id: new mongoose.Types.ObjectId(),
  name: `Project ${Math.random().toString(36).substr(2, 9)}`,
  client: clientId,
  status: 'active',
  description: 'Test project description'
});

const generateUser = (departmentId) => ({
  _id: new mongoose.Types.ObjectId(),
  name: `User ${Math.random().toString(36).substr(2, 9)}`,
  email: `user${Math.random().toString(36).substr(2, 5)}@example.com`,
  role: 'employee',
  department: departmentId,
  status: 'active'
});

const generateDepartment = () => ({
  _id: new mongoose.Types.ObjectId(),
  name: `Department ${Math.random().toString(36).substr(2, 9)}`,
  status: 'active'
});

const generateWorkEntry = (clientId, projectId, employeeId, departmentId) => {
  const statuses = ['scheduled', 'in-progress', 'completed', 'overdue', 'cancelled'];
  const priorities = ['low', 'medium', 'high', 'urgent'];
  const workTypes = ['work-item', 'meeting', 'deadline', 'review'];
  
  const startDate = new Date();
  startDate.setDate(startDate.getDate() + Math.floor(Math.random() * 30) - 15); // ±15 days
  
  const endDate = new Date(startDate);
  endDate.setHours(endDate.getHours() + Math.floor(Math.random() * 8) + 1); // 1-8 hours later
  
  return {
    _id: new mongoose.Types.ObjectId(),
    title: `Work Entry ${Math.random().toString(36).substr(2, 9)}`,
    description: 'Test work entry description',
    client: clientId,
    project: projectId,
    assignedTo: employeeId,
    department: departmentId,
    status: statuses[Math.floor(Math.random() * statuses.length)],
    priority: priorities[Math.floor(Math.random() * priorities.length)],
    workType: workTypes[Math.floor(Math.random() * workTypes.length)],
    startDate,
    endDate,
    dueDate: new Date(endDate.getTime() + Math.random() * 7 * 24 * 60 * 60 * 1000), // Within 7 days
    timeTracking: {
      estimatedHours: Math.floor(Math.random() * 8) + 1,
      actualHours: Math.floor(Math.random() * 10)
    },
    progress: Math.floor(Math.random() * 101),
    createdBy: employeeId,
    isAutoGenerated: false
  };
};

// Property-based test runner (simplified version of fast-check)
const runPropertyTest = (testFn, iterations = 100) => {
  for (let i = 0; i < iterations; i++) {
    try {
      testFn();
    } catch (error) {
      throw new Error(`Property test failed on iteration ${i + 1}: ${error.message}`);
    }
  }
};

describe('Enhanced Work Calendar Property Tests', () => {
  
  /**
   * **Feature: admin-work-management-enhancement, Property 1: Client Filter Completeness**
   * For any client selection, filtering by that client should return all and only 
   * work entries associated with projects belonging to that client
   */
  test('client filtering returns complete and accurate results', () => {
    runPropertyTest(() => {
      // Generate test data
      const clients = Array.from({ length: 3 }, () => generateClient());
      const departments = Array.from({ length: 2 }, () => generateDepartment());
      const projects = [];
      const users = [];
      const workEntries = [];

      // Create projects for each client
      clients.forEach(client => {
        const clientProjects = Array.from({ length: 2 }, () => generateProject(client._id));
        projects.push(...clientProjects);
      });

      // Create users
      departments.forEach(dept => {
        const deptUsers = Array.from({ length: 2 }, () => generateUser(dept._id));
        users.push(...deptUsers);
      });

      // Create work entries for each project
      projects.forEach(project => {
        const projectWorkEntries = Array.from({ length: 3 }, () => 
          generateWorkEntry(
            project.client,
            project._id,
            users[Math.floor(Math.random() * users.length)]._id,
            departments[Math.floor(Math.random() * departments.length)]._id
          )
        );
        workEntries.push(...projectWorkEntries);
      });

      // Test client filtering
      const selectedClient = clients[0];
      const expectedWorkEntries = workEntries.filter(entry => 
        entry.client.toString() === selectedClient._id.toString()
      );

      // Simulate filter application
      const filteredEntries = workEntries.filter(entry => {
        // This simulates the buildAdvancedFilter function behavior
        return entry.client.toString() === selectedClient._id.toString();
      });

      // Verify completeness: all work for the client is returned
      expect(filteredEntries.length).toBe(expectedWorkEntries.length);
      
      // Verify accuracy: only work for the selected client is returned
      filteredEntries.forEach(entry => {
        expect(entry.client.toString()).toBe(selectedClient._id.toString());
      });

      // Verify no work from other clients is included
      const otherClientWork = filteredEntries.filter(entry => 
        entry.client.toString() !== selectedClient._id.toString()
      );
      expect(otherClientWork.length).toBe(0);
    });
  });

  /**
   * **Feature: admin-work-management-enhancement, Property 2: Filter Combination Consistency**
   * For any combination of filters applied simultaneously, the results should satisfy 
   * all filter conditions with proper boolean logic
   */
  test('filter combinations work correctly with AND logic', () => {
    runPropertyTest(() => {
      // Generate test data
      const clients = Array.from({ length: 2 }, () => generateClient());
      const departments = Array.from({ length: 2 }, () => generateDepartment());
      const projects = Array.from({ length: 2 }, () => generateProject(clients[0]._id));
      const users = Array.from({ length: 2 }, () => generateUser(departments[0]._id));
      
      const workEntries = Array.from({ length: 10 }, () => 
        generateWorkEntry(
          clients[Math.floor(Math.random() * clients.length)]._id,
          projects[Math.floor(Math.random() * projects.length)]._id,
          users[Math.floor(Math.random() * users.length)]._id,
          departments[Math.floor(Math.random() * departments.length)]._id
        )
      );

      // Apply multiple filters
      const filters = {
        client: clients[0]._id.toString(),
        status: 'in-progress',
        priority: 'high'
      };

      // Simulate combined filter application
      const filteredEntries = workEntries.filter(entry => {
        let matches = true;
        
        if (filters.client && filters.client !== 'all') {
          matches = matches && entry.client.toString() === filters.client;
        }
        
        if (filters.status && filters.status !== 'all') {
          matches = matches && entry.status === filters.status;
        }
        
        if (filters.priority && filters.priority !== 'all') {
          matches = matches && entry.priority === filters.priority;
        }
        
        return matches;
      });

      // Verify all results match ALL filter criteria
      filteredEntries.forEach(entry => {
        expect(entry.client.toString()).toBe(filters.client);
        expect(entry.status).toBe(filters.status);
        expect(entry.priority).toBe(filters.priority);
      });

      // Verify no entries that don't match all criteria are included
      const expectedCount = workEntries.filter(entry => 
        entry.client.toString() === filters.client &&
        entry.status === filters.status &&
        entry.priority === filters.priority
      ).length;
      
      expect(filteredEntries.length).toBe(expectedCount);
    });
  });

  /**
   * Test helper function for building advanced filters
   */
  test('buildAdvancedFilter creates correct MongoDB queries', async () => {
    const filterParams = {
      client: 'client123',
      project: 'project456',
      status: 'in-progress',
      priority: 'high',
      search: 'test search'
    };

    // Mock the buildAdvancedFilter function behavior
    const mockBuildAdvancedFilter = (params) => {
      const filter = {};
      
      if (params.client && params.client !== 'all') {
        filter.client = params.client;
      }
      
      if (params.project && params.project !== 'all') {
        filter.project = params.project;
      }
      
      if (params.status && params.status !== 'all') {
        filter.status = params.status;
      }
      
      if (params.priority && params.priority !== 'all') {
        filter.priority = params.priority;
      }
      
      if (params.search && params.search.trim()) {
        const searchRegex = new RegExp(params.search.trim(), 'i');
        filter.$or = [
          { title: searchRegex },
          { description: searchRegex }
        ];
      }
      
      return filter;
    };

    const result = mockBuildAdvancedFilter(filterParams);

    expect(result.client).toBe('client123');
    expect(result.project).toBe('project456');
    expect(result.status).toBe('in-progress');
    expect(result.priority).toBe('high');
    expect(result.$or).toBeDefined();
    expect(result.$or.length).toBe(2);
  });

  /**
   * **Feature: admin-work-management-enhancement, Property 6: Analytics Accuracy and Responsiveness**
   * For any set of filtered work data, calculated analytics should be mathematically 
   * correct and update when filters change
   */
  test('analytics accuracy and responsiveness', () => {
    runPropertyTest(() => {
      // Generate comprehensive test data
      const clients = Array.from({ length: 3 }, () => generateClient());
      const departments = Array.from({ length: 2 }, () => generateDepartment());
      const projects = [];
      const users = [];
      
      // Create projects for each client
      clients.forEach(client => {
        const clientProjects = Array.from({ length: 2 }, () => generateProject(client._id));
        projects.push(...clientProjects);
      });

      // Create users for each department
      departments.forEach(dept => {
        const deptUsers = Array.from({ length: 2 }, () => generateUser(dept._id));
        users.push(...deptUsers);
      });

      // Generate work entries with known distribution
      const workEntries = [];
      const statuses = ['completed', 'in-progress', 'overdue', 'scheduled'];
      const priorities = ['low', 'medium', 'high', 'urgent'];
      
      // Create 20 work entries with controlled distribution
      for (let i = 0; i < 20; i++) {
        const entry = generateWorkEntry(
          clients[i % clients.length]._id,
          projects[i % projects.length]._id,
          users[i % users.length]._id,
          departments[i % departments.length]._id
        );
        
        // Override with controlled values for testing
        entry.status = statuses[i % statuses.length];
        entry.priority = priorities[i % priorities.length];
        entry.timeTracking = {
          estimatedHours: (i % 8) + 1, // 1-8 hours
          actualHours: (i % 10) + 1     // 1-10 hours
        };
        entry.progress = (i % 11) * 10; // 0, 10, 20, ..., 100
        
        workEntries.push(entry);
      }

      // Test 1: Overall Analytics Accuracy
      const calculateOverallAnalytics = (entries) => {
        const total = entries.length;
        const completed = entries.filter(e => e.status === 'completed').length;
        const inProgress = entries.filter(e => e.status === 'in-progress').length;
        const overdue = entries.filter(e => e.status === 'overdue').length;
        const scheduled = entries.filter(e => e.status === 'scheduled').length;
        const totalEstimated = entries.reduce((sum, e) => sum + e.timeTracking.estimatedHours, 0);
        const totalActual = entries.reduce((sum, e) => sum + e.timeTracking.actualHours, 0);
        const avgProgress = entries.reduce((sum, e) => sum + e.progress, 0) / entries.length;
        
        return {
          totalWork: total,
          completedWork: completed,
          inProgressWork: inProgress,
          overdueWork: overdue,
          scheduledWork: scheduled,
          totalEstimatedHours: totalEstimated,
          totalActualHours: totalActual,
          avgProgress: Math.round(avgProgress),
          completionRate: total > 0 ? Math.round((completed / total) * 100) : 0,
          overdueRate: total > 0 ? Math.round((overdue / total) * 100) : 0,
          efficiency: totalEstimated > 0 ? Math.round((totalActual / totalEstimated) * 100) : 0
        };
      };

      const overallAnalytics = calculateOverallAnalytics(workEntries);
      
      // Verify overall calculations
      expect(overallAnalytics.totalWork).toBe(20);
      expect(overallAnalytics.completedWork + overallAnalytics.inProgressWork + 
             overallAnalytics.overdueWork + overallAnalytics.scheduledWork).toBe(20);
      expect(overallAnalytics.completionRate).toBeGreaterThanOrEqual(0);
      expect(overallAnalytics.completionRate).toBeLessThanOrEqual(100);

      // Test 2: Client-Focused Analytics Accuracy
      const calculateClientAnalytics = (entries) => {
        const clientGroups = {};
        
        entries.forEach(entry => {
          const clientId = entry.client.toString();
          if (!clientGroups[clientId]) {
            clientGroups[clientId] = [];
          }
          clientGroups[clientId].push(entry);
        });

        return Object.keys(clientGroups).map(clientId => {
          const clientEntries = clientGroups[clientId];
          const analytics = calculateOverallAnalytics(clientEntries);
          return {
            clientId,
            ...analytics
          };
        });
      };

      const clientAnalytics = calculateClientAnalytics(workEntries);
      
      // Verify client analytics sum to overall totals
      const totalFromClients = clientAnalytics.reduce((sum, client) => sum + client.totalWork, 0);
      expect(totalFromClients).toBe(overallAnalytics.totalWork);

      const completedFromClients = clientAnalytics.reduce((sum, client) => sum + client.completedWork, 0);
      expect(completedFromClients).toBe(overallAnalytics.completedWork);

      // Test 3: Filter Responsiveness
      // Apply client filter and verify analytics update correctly
      const selectedClient = clients[0];
      const filteredEntries = workEntries.filter(entry => 
        entry.client.toString() === selectedClient._id.toString()
      );
      
      const filteredAnalytics = calculateOverallAnalytics(filteredEntries);
      
      // Verify filtered analytics are different from overall (unless all work is for one client)
      if (filteredEntries.length < workEntries.length) {
        expect(filteredAnalytics.totalWork).toBeLessThan(overallAnalytics.totalWork);
      }
      
      // Verify filtered analytics are mathematically correct
      expect(filteredAnalytics.totalWork).toBe(filteredEntries.length);
      
      // Test 4: Priority Distribution Accuracy
      const calculatePriorityDistribution = (entries) => {
        const distribution = { urgent: 0, high: 0, medium: 0, low: 0 };
        entries.forEach(entry => {
          if (distribution.hasOwnProperty(entry.priority)) {
            distribution[entry.priority]++;
          }
        });
        return distribution;
      };

      const priorityDistribution = calculatePriorityDistribution(workEntries);
      const totalFromPriorities = Object.values(priorityDistribution).reduce((sum, count) => sum + count, 0);
      expect(totalFromPriorities).toBe(workEntries.length);

      // Test 5: Time-based Analytics Accuracy
      const totalEstimatedHours = workEntries.reduce((sum, entry) => sum + entry.timeTracking.estimatedHours, 0);
      const totalActualHours = workEntries.reduce((sum, entry) => sum + entry.timeTracking.actualHours, 0);
      
      expect(overallAnalytics.totalEstimatedHours).toBe(totalEstimatedHours);
      expect(overallAnalytics.totalActualHours).toBe(totalActualHours);
      
      // Verify efficiency calculation
      const expectedEfficiency = totalEstimatedHours > 0 ? 
        Math.round((totalActualHours / totalEstimatedHours) * 100) : 0;
      expect(overallAnalytics.efficiency).toBe(expectedEfficiency);

      // Test 6: Analytics Responsiveness to Data Changes
      // Simulate adding a new work entry
      const newEntry = generateWorkEntry(
        clients[0]._id,
        projects[0]._id,
        users[0]._id,
        departments[0]._id
      );
      newEntry.status = 'completed';
      newEntry.timeTracking = { estimatedHours: 5, actualHours: 4 };
      
      const updatedEntries = [...workEntries, newEntry];
      const updatedAnalytics = calculateOverallAnalytics(updatedEntries);
      
      // Verify analytics updated correctly
      expect(updatedAnalytics.totalWork).toBe(overallAnalytics.totalWork + 1);
      expect(updatedAnalytics.completedWork).toBe(overallAnalytics.completedWork + 1);
      expect(updatedAnalytics.totalEstimatedHours).toBe(overallAnalytics.totalEstimatedHours + 5);
      expect(updatedAnalytics.totalActualHours).toBe(overallAnalytics.totalActualHours + 4);
    });
  });

  /**
   * Test bulk operations integrity
   */
  test('bulk operations update all selected entries correctly', () => {
    runPropertyTest(() => {
      // Generate test work entries
      const workEntries = Array.from({ length: 10 }, (_, index) => ({
        _id: new mongoose.Types.ObjectId(),
        title: `Work Entry ${index}`,
        status: 'scheduled',
        priority: 'medium',
        assignedTo: new mongoose.Types.ObjectId()
      }));

      // Select random entries for bulk operation
      const selectedIds = workEntries
        .slice(0, Math.floor(Math.random() * 5) + 1)
        .map(entry => entry._id.toString());

      // Simulate bulk status update
      const newStatus = 'in-progress';
      const updatedEntries = workEntries.map(entry => {
        if (selectedIds.includes(entry._id.toString())) {
          return { ...entry, status: newStatus };
        }
        return entry;
      });

      // Verify all selected entries were updated
      selectedIds.forEach(id => {
        const updatedEntry = updatedEntries.find(entry => entry._id.toString() === id);
        expect(updatedEntry.status).toBe(newStatus);
      });

      // Verify non-selected entries were not updated
      const nonSelectedEntries = updatedEntries.filter(entry => 
        !selectedIds.includes(entry._id.toString())
      );
      nonSelectedEntries.forEach(entry => {
        expect(entry.status).toBe('scheduled'); // Original status
      });

      // Verify correct count of updated entries
      const actualUpdatedCount = updatedEntries.filter(entry => entry.status === newStatus).length;
      expect(actualUpdatedCount).toBe(selectedIds.length);
    });
  });
});

// Export for use in other test files
export {
  generateClient,
  generateProject,
  generateUser,
  generateDepartment,
  generateWorkEntry,
  runPropertyTest
};