import WorkCalendar from "../models/workCalendarModel.js";
import WorkItem from "../models/workItemModel.js";
import Project from "../models/projectModel.js";
import Department from "../models/departmentModel.js";
import User from "../models/userModel.js";
import Client from "../models/clientModel.js";
import CalendarEvent from "../models/calendarEventModel.js";
import logger from "../utils/logger.js";
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import moment from "moment";

/**
 * Comprehensive Work Calendar Controller
 * Handles employee work calendars, admin overview, filtering, and PDF exports
 */

// ============================================
// EMPLOYEE WORK CALENDAR
// ============================================

/**
 * Get employee's personal work calendar
 * Shows all work assigned to the employee
 */
export const getEmployeeWorkCalendar = async (req, res) => {
  try {
    const employeeId = req.params.employeeId || req.user.id;
    const { 
      startDate, 
      endDate, 
      status, 
      workType, 
      project, 
      priority,
      view = 'calendar' 
    } = req.query;

    // Use both console.log and console.error to ensure visibility
    console.error(`[CALENDAR] Getting work calendar for employee: ${employeeId}`);
    console.error(`[CALENDAR] Request user: ${req.user.id}, role: ${req.user.role}`);
    console.error(`[CALENDAR] Query params:`, { startDate, endDate, status, workType, project, priority, view });

    // Permission check: employees can only see their own calendar
    if (req.user.role === 'employee' && employeeId !== req.user.id) {
      console.error(`[CALENDAR] Permission denied: employee ${req.user.id} trying to access ${employeeId}'s calendar`);
      return res.status(403).json({ 
        success: false, 
        message: "You can only view your own work calendar" 
      });
    }

    // Build date range filter - temporarily disabled for debugging
    const dateFilter = {};
    // Commenting out date filter to see all work calendar entries
    // if (startDate && endDate) {
    //   dateFilter.$or = [
    //     {
    //       startDate: { 
    //         $gte: new Date(startDate), 
    //         $lte: new Date(endDate) 
    //       }
    //     },
    //     {
    //       endDate: { 
    //         $gte: new Date(startDate), 
    //         $lte: new Date(endDate) 
    //       }
    //     },
    //     {
    //       $and: [
    //         { startDate: { $lte: new Date(startDate) } },
    //         { endDate: { $gte: new Date(endDate) } }
    //       ]
    //     }
    //   ];
    // }

    // Get work calendar entries - show ALL entries for debugging
    const workCalendarQuery = {
      assignedTo: employeeId
      // Temporarily not applying date filter: ...dateFilter
    };

    if (status) workCalendarQuery.status = status;
    if (workType) workCalendarQuery.workType = workType;
    if (project) workCalendarQuery.project = project;
    if (priority) workCalendarQuery.priority = priority;

    const workCalendarEntries = await WorkCalendar.find(workCalendarQuery)
      .populate('project', 'name client status')
      .populate('client', 'name')
      .populate('department', 'name')
      .populate('assignedTo', 'name email')
      .populate('collaborators.user', 'name email')
      .sort({ startDate: 1 });

    console.error(`[CALENDAR] Found ${workCalendarEntries.length} work calendar entries for employee ${employeeId}`);
    if (workCalendarEntries.length > 0) {
      console.error('[CALENDAR] Work calendar entries:', workCalendarEntries.map(entry => ({
        id: entry._id,
        title: entry.title,
        startDate: entry.startDate,
        endDate: entry.endDate,
        isAutoGenerated: entry.isAutoGenerated,
        sourceModel: entry.sourceModel
      })));
    }

    // Get work items for the employee (to auto-generate calendar entries if needed)
    const workItemsQuery = {
      assignedTo: employeeId
    };

    // For work items, use a broader date range to show all relevant items
    if (startDate && endDate) {
      const extendedStartDate = new Date(startDate);
      extendedStartDate.setDate(extendedStartDate.getDate() - 30); // 30 days before
      const extendedEndDate = new Date(endDate);
      extendedEndDate.setDate(extendedEndDate.getDate() + 30); // 30 days after
      
      workItemsQuery.dueDate = {
        $gte: extendedStartDate,
        $lte: extendedEndDate
      };
    }

    const workItems = await WorkItem.find(workItemsQuery)
      .populate('project', 'name client status departments')
      .populate('assignedTo', 'name email')
      .sort({ dueDate: 1 });

    logger.info(`Found ${workItems.length} work items for employee ${employeeId}`);

    // Auto-generate calendar entries for work items that don't have them
    const existingWorkItemIds = workCalendarEntries
      .filter(entry => entry.sourceModel === 'WorkItem')
      .map(entry => entry.sourceId.toString());

    const newCalendarEntries = [];
    for (const workItem of workItems) {
      if (!existingWorkItemIds.includes(workItem._id.toString())) {
        const calendarEntry = await createWorkCalendarEntry(workItem);
        if (calendarEntry) {
          newCalendarEntries.push(calendarEntry);
        }
      }
    }

    // Combine existing and new entries
    const allEntries = [...workCalendarEntries, ...newCalendarEntries];

    // Get employee details
    const employee = await User.findById(employeeId)
      .populate('department', 'name')
      .select('name email role department');

    // Calculate analytics
    const analytics = calculateEmployeeAnalytics(allEntries, workItems);

    // Format response based on view type
    let formattedEntries = allEntries;
    if (view === 'calendar') {
      formattedEntries = formatForCalendarView(allEntries);
    } else if (view === 'timeline') {
      formattedEntries = formatForTimelineView(allEntries);
    } else if (view === 'list') {
      formattedEntries = formatForListView(allEntries);
    }

    console.error(`[CALENDAR] Sending response with ${formattedEntries.length} work calendar entries and ${workItems.length} work items`);
    
    const responseData = {
      success: true,
      data: {
        employee,
        workCalendar: formattedEntries,
        workItems,
        analytics,
        filters: {
          startDate,
          endDate,
          status,
          workType,
          project,
          priority,
          view
        }
      }
    };
    
    console.error('[CALENDAR] Response data summary:', {
      workCalendarCount: formattedEntries.length,
      workItemsCount: workItems.length,
      employeeName: employee?.name
    });
    
    res.status(200).json(responseData);

  } catch (error) {
    logger.error('Error in getEmployeeWorkCalendar:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch employee work calendar',
      error: error.message
    });
  }
};

// ============================================
// ADMIN COMPREHENSIVE OVERVIEW
// ============================================

/**
 * Get comprehensive admin overview with advanced filtering
 * Admin can see all work across projects, employees, departments
 */
export const getAdminWorkOverview = async (req, res) => {
  try {
    // Only admin, superadmin, hr, manager can access
    if (!['admin', 'superadmin', 'hr', 'manager'].includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: 'Access denied. Admin privileges required.'
      });
    }

    const {
      startDate,
      endDate,
      department,
      project,
      client,
      employee,
      status,
      workType,
      priority,
      view = 'overview',
      groupBy = 'project',
      sortBy = 'startDate',
      sortOrder = 'asc'
    } = req.query;

    // Build comprehensive filter
    const filter = {};
    
    if (startDate && endDate) {
      filter.$or = [
        {
          startDate: { 
            $gte: new Date(startDate), 
            $lte: new Date(endDate) 
          }
        },
        {
          endDate: { 
            $gte: new Date(startDate), 
            $lte: new Date(endDate) 
          }
        }
      ];
    }

    if (department) filter.department = department;
    if (project) filter.project = project;
    if (client) filter.client = client;
    if (employee) filter.assignedTo = employee;
    if (status) filter.status = status;
    if (workType) filter.workType = workType;
    if (priority) filter.priority = priority;

    // Get all work calendar entries
    const workCalendarEntries = await WorkCalendar.find(filter)
      .populate('project', 'name client status departments')
      .populate('client', 'name email')
      .populate('department', 'name')
      .populate('assignedTo', 'name email role department')
      .populate('createdBy', 'name email')
      .populate('collaborators.user', 'name email')
      .sort({ [sortBy]: sortOrder === 'asc' ? 1 : -1 });

    // Get related work items
    const workItemFilter = {};
    if (department) {
      // Get projects in this department
      const deptProjects = await Project.find({ departments: department }).select('_id');
      workItemFilter.project = { $in: deptProjects.map(p => p._id) };
    }
    if (project) workItemFilter.project = project;
    if (employee) workItemFilter.assignedTo = employee;
    if (status) {
      // Map work calendar status to work item status
      const statusMap = {
        'scheduled': 'To Do',
        'in-progress': 'In Progress',
        'completed': 'Done',
        'overdue': ['To Do', 'In Progress', 'Review']
      };
      workItemFilter.status = statusMap[status] || status;
    }

    const workItems = await WorkItem.find(workItemFilter)
      .populate('project', 'name client status')
      .populate('assignedTo', 'name email role department')
      .sort({ dueDate: 1 });

    // Get comprehensive analytics
    const analytics = await getComprehensiveAnalytics(filter);

    // Group data based on groupBy parameter
    let groupedData = {};
    if (groupBy === 'project') {
      groupedData = groupByProject(workCalendarEntries, workItems);
    } else if (groupBy === 'employee') {
      groupedData = groupByEmployee(workCalendarEntries, workItems);
    } else if (groupBy === 'department') {
      groupedData = groupByDepartment(workCalendarEntries, workItems);
    } else if (groupBy === 'client') {
      groupedData = groupByClient(workCalendarEntries, workItems);
    } else if (groupBy === 'date') {
      groupedData = groupByDate(workCalendarEntries, workItems);
    }

    // Get filter options for frontend
    const filterOptions = await getFilterOptions();

    res.status(200).json({
      success: true,
      data: {
        workCalendar: workCalendarEntries,
        workItems,
        groupedData,
        analytics,
        filterOptions,
        filters: {
          startDate,
          endDate,
          department,
          project,
          client,
          employee,
          status,
          workType,
          priority,
          view,
          groupBy,
          sortBy,
          sortOrder
        },
        totalRecords: workCalendarEntries.length
      }
    });

  } catch (error) {
    logger.error('Error in getAdminWorkOverview:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch admin work overview',
      error: error.message
    });
  }
};

// ============================================
// PDF EXPORT FUNCTIONALITY
// ============================================

/**
 * Generate and download PDF report
 * Supports various report types and filters
 */
export const generateWorkReportPDF = async (req, res) => {
  try {
    // Only admin, superadmin, hr, manager can generate reports
    if (!['admin', 'superadmin', 'hr', 'manager'].includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: 'Access denied. Admin privileges required.'
      });
    }

    const {
      reportType = 'comprehensive',
      startDate,
      endDate,
      department,
      project,
      client,
      employee,
      status,
      workType,
      priority,
      groupBy = 'project',
      includeAnalytics = true,
      includeCharts = false
    } = req.body;

    // Get data based on filters (reuse admin overview logic)
    const filter = {};
    if (startDate && endDate) {
      filter.$or = [
        {
          startDate: { 
            $gte: new Date(startDate), 
            $lte: new Date(endDate) 
          }
        },
        {
          endDate: { 
            $gte: new Date(startDate), 
            $lte: new Date(endDate) 
          }
        }
      ];
    }

    if (department) filter.department = department;
    if (project) filter.project = project;
    if (client) filter.client = client;
    if (employee) filter.assignedTo = employee;
    if (status) filter.status = status;
    if (workType) filter.workType = workType;
    if (priority) filter.priority = priority;

    const workCalendarEntries = await WorkCalendar.find(filter)
      .populate('project', 'name client status departments')
      .populate('client', 'name email')
      .populate('department', 'name')
      .populate('assignedTo', 'name email role department')
      .populate('createdBy', 'name email')
      .sort({ startDate: 1 });

    const workItems = await WorkItem.find({})
      .populate('project', 'name client status')
      .populate('assignedTo', 'name email role department')
      .sort({ dueDate: 1 });

    // Generate PDF
    const pdfBuffer = await generatePDFReport({
      reportType,
      workCalendarEntries,
      workItems,
      filters: { startDate, endDate, department, project, client, employee, status, workType, priority },
      groupBy,
      includeAnalytics,
      includeCharts,
      generatedBy: req.user
    });

    // Set response headers for PDF download
    const filename = `work-report-${moment().format('YYYY-MM-DD-HHmm')}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);

    res.send(pdfBuffer);

  } catch (error) {
    logger.error('Error in generateWorkReportPDF:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate PDF report',
      error: error.message
    });
  }
};

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Auto-create work calendar entry from work item
 */
const createWorkCalendarEntry = async (workItem) => {
  try {
    // Check if entry already exists
    const existing = await WorkCalendar.findOne({
      sourceId: workItem._id,
      sourceModel: 'WorkItem'
    });

    if (existing) {
      logger.info(`Calendar entry already exists for work item: ${workItem._id}`);
      return null;
    }

    // Determine work type based on work item
    let workType = 'work-item';
    if (workItem.type === 'content') {
      workType = 'work-item'; // Keep as work-item for consistency
    }

    // Calculate start and end dates based on due date
    const dueDate = new Date(workItem.dueDate);
    
    // Set start date to the day before due date at 9 AM (or same day if due today)
    const startDate = new Date(dueDate);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    if (dueDate.getTime() <= today.getTime()) {
      // If due today or overdue, start immediately
      startDate.setHours(9, 0, 0, 0);
    } else {
      // Start the day before due date
      startDate.setDate(startDate.getDate() - 1);
      startDate.setHours(9, 0, 0, 0);
    }
    
    // End date is the due date at 5 PM
    const endDate = new Date(dueDate);
    endDate.setHours(17, 0, 0, 0);

    // Get project details for department and client
    const project = await Project.findById(workItem.project)
      .populate('departments')
      .populate('client');

    if (!project) {
      logger.error(`Project not found for work item: ${workItem._id}`);
      return null;
    }

    // Get department - use first department from project
    let departmentId = null;
    if (project.departments && project.departments.length > 0) {
      departmentId = project.departments[0]._id;
    } else if (project.department) {
      departmentId = project.department;
    }

    if (!departmentId) {
      logger.error(`No department found for project: ${project._id}`);
      return null;
    }

    const calendarEntry = new WorkCalendar({
      title: workItem.title,
      description: workItem.description || `Work item: ${workItem.title}`,
      workType,
      sourceId: workItem._id,
      sourceModel: 'WorkItem',
      assignedTo: workItem.assignedTo,
      department: departmentId,
      project: workItem.project,
      client: project?.client?._id,
      startDate,
      endDate,
      dueDate: workItem.dueDate,
      status: mapWorkItemStatusToCalendarStatus(workItem.status),
      priority: workItem.priority || 'medium',
      timeTracking: {
        estimatedHours: workItem.estimatedHours || 8, // Default 8 hours
        actualHours: workItem.actualHours || 0
      },
      isAutoGenerated: true,
      autoGeneratedBy: 'work-item-sync',
      createdBy: workItem.createdBy,
      tags: workItem.tags || []
    });

    await calendarEntry.save();
    logger.info(`Created calendar entry for work item: ${workItem._id} - ${workItem.title}`);
    return calendarEntry;

  } catch (error) {
    logger.error('Error creating work calendar entry:', error);
    logger.error('Work item data:', JSON.stringify(workItem, null, 2));
    return null;
  }
};

/**
 * Map work item status to calendar status
 */
const mapWorkItemStatusToCalendarStatus = (workItemStatus) => {
  const statusMap = {
    'To Do': 'scheduled',
    'In Progress': 'in-progress',
    'Review': 'in-progress',
    'Done': 'completed'
  };
  return statusMap[workItemStatus] || 'scheduled';
};

/**
 * Calculate employee analytics
 */
const calculateEmployeeAnalytics = (workCalendarEntries, workItems) => {
  const now = new Date();
  
  return {
    totalWork: workCalendarEntries.length,
    completedWork: workCalendarEntries.filter(w => w.status === 'completed').length,
    inProgressWork: workCalendarEntries.filter(w => w.status === 'in-progress').length,
    scheduledWork: workCalendarEntries.filter(w => w.status === 'scheduled').length,
    overdueWork: workCalendarEntries.filter(w => w.isOverdue).length,
    totalWorkItems: workItems.length,
    completedWorkItems: workItems.filter(w => w.status === 'Done').length,
    overdueWorkItems: workItems.filter(w => w.isOverdue).length,
    totalEstimatedHours: workCalendarEntries.reduce((sum, w) => sum + (w.timeTracking?.estimatedHours || 0), 0),
    totalActualHours: workCalendarEntries.reduce((sum, w) => sum + (w.timeTracking?.actualHours || 0), 0),
    averageEfficiency: calculateAverageEfficiency(workCalendarEntries),
    workloadByPriority: {
      urgent: workCalendarEntries.filter(w => w.priority === 'urgent').length,
      high: workCalendarEntries.filter(w => w.priority === 'high').length,
      medium: workCalendarEntries.filter(w => w.priority === 'medium').length,
      low: workCalendarEntries.filter(w => w.priority === 'low').length
    }
  };
};

/**
 * Get comprehensive analytics for admin
 */
const getComprehensiveAnalytics = async (filter) => {
  const analytics = await WorkCalendar.getAnalytics(filter);
  
  // Additional department-wise analytics
  const departmentAnalytics = await WorkCalendar.aggregate([
    { $match: filter },
    {
      $lookup: {
        from: 'departments',
        localField: 'department',
        foreignField: '_id',
        as: 'departmentInfo'
      }
    },
    { $unwind: '$departmentInfo' },
    {
      $group: {
        _id: '$department',
        departmentName: { $first: '$departmentInfo.name' },
        totalWork: { $sum: 1 },
        completedWork: { $sum: { $cond: [{ $eq: ['$status', 'completed'] }, 1, 0] } },
        overdueWork: { $sum: { $cond: [{ $eq: ['$status', 'overdue'] }, 1, 0] } },
        totalHours: { $sum: '$timeTracking.actualHours' }
      }
    }
  ]);

  // Project-wise analytics
  const projectAnalytics = await WorkCalendar.aggregate([
    { $match: filter },
    {
      $lookup: {
        from: 'projects',
        localField: 'project',
        foreignField: '_id',
        as: 'projectInfo'
      }
    },
    { $unwind: '$projectInfo' },
    {
      $group: {
        _id: '$project',
        projectName: { $first: '$projectInfo.name' },
        totalWork: { $sum: 1 },
        completedWork: { $sum: { $cond: [{ $eq: ['$status', 'completed'] }, 1, 0] } },
        overdueWork: { $sum: { $cond: [{ $eq: ['$status', 'overdue'] }, 1, 0] } }
      }
    }
  ]);

  return {
    overall: analytics[0] || {},
    byDepartment: departmentAnalytics,
    byProject: projectAnalytics
  };
};

/**
 * Format entries for different view types
 */
const formatForCalendarView = (entries) => {
  return entries.map(entry => ({
    id: entry._id,
    title: entry.title,
    start: entry.startDate,
    end: entry.endDate,
    allDay: entry.isAllDay,
    backgroundColor: getStatusColor(entry.status),
    borderColor: getPriorityColor(entry.priority),
    resource: entry
  }));
};

const formatForTimelineView = (entries) => {
  // Group by date and sort chronologically
  const grouped = {};
  entries.forEach(entry => {
    const date = moment(entry.startDate).format('YYYY-MM-DD');
    if (!grouped[date]) grouped[date] = [];
    grouped[date].push(entry);
  });
  
  return Object.keys(grouped)
    .sort()
    .map(date => ({
      date,
      entries: grouped[date].sort((a, b) => new Date(a.startDate) - new Date(b.startDate))
    }));
};

const formatForListView = (entries) => {
  return entries.sort((a, b) => {
    // Sort by priority first, then by due date
    const priorityOrder = { urgent: 4, high: 3, medium: 2, low: 1 };
    const aPriority = priorityOrder[a.priority] || 0;
    const bPriority = priorityOrder[b.priority] || 0;
    
    if (aPriority !== bPriority) {
      return bPriority - aPriority;
    }
    
    return new Date(a.startDate) - new Date(b.startDate);
  });
};

/**
 * Grouping functions
 */
const groupByProject = (workCalendarEntries, workItems) => {
  const grouped = {};
  
  workCalendarEntries.forEach(entry => {
    const projectId = entry.project?._id?.toString() || 'unassigned';
    const projectName = entry.project?.name || 'Unassigned';
    
    if (!grouped[projectId]) {
      grouped[projectId] = {
        project: entry.project,
        workCalendar: [],
        workItems: [],
        analytics: { total: 0, completed: 0, overdue: 0 }
      };
    }
    
    grouped[projectId].workCalendar.push(entry);
    grouped[projectId].analytics.total++;
    if (entry.status === 'completed') grouped[projectId].analytics.completed++;
    if (entry.isOverdue) grouped[projectId].analytics.overdue++;
  });
  
  workItems.forEach(item => {
    const projectId = item.project?._id?.toString() || 'unassigned';
    
    if (grouped[projectId]) {
      grouped[projectId].workItems.push(item);
    }
  });
  
  return grouped;
};

const groupByEmployee = (workCalendarEntries, workItems) => {
  const grouped = {};
  
  workCalendarEntries.forEach(entry => {
    const employeeId = entry.assignedTo?._id?.toString() || 'unassigned';
    
    if (!grouped[employeeId]) {
      grouped[employeeId] = {
        employee: entry.assignedTo,
        workCalendar: [],
        workItems: [],
        analytics: { total: 0, completed: 0, overdue: 0 }
      };
    }
    
    grouped[employeeId].workCalendar.push(entry);
    grouped[employeeId].analytics.total++;
    if (entry.status === 'completed') grouped[employeeId].analytics.completed++;
    if (entry.isOverdue) grouped[employeeId].analytics.overdue++;
  });
  
  return grouped;
};

const groupByDepartment = (workCalendarEntries, workItems) => {
  const grouped = {};
  
  workCalendarEntries.forEach(entry => {
    const deptId = entry.department?._id?.toString() || 'unassigned';
    
    if (!grouped[deptId]) {
      grouped[deptId] = {
        department: entry.department,
        workCalendar: [],
        workItems: [],
        analytics: { total: 0, completed: 0, overdue: 0 }
      };
    }
    
    grouped[deptId].workCalendar.push(entry);
    grouped[deptId].analytics.total++;
    if (entry.status === 'completed') grouped[deptId].analytics.completed++;
    if (entry.isOverdue) grouped[deptId].analytics.overdue++;
  });
  
  return grouped;
};

const groupByClient = (workCalendarEntries, workItems) => {
  const grouped = {};
  
  workCalendarEntries.forEach(entry => {
    const clientId = entry.client?._id?.toString() || 'internal';
    
    if (!grouped[clientId]) {
      grouped[clientId] = {
        client: entry.client || { name: 'Internal Work' },
        workCalendar: [],
        workItems: [],
        analytics: { total: 0, completed: 0, overdue: 0 }
      };
    }
    
    grouped[clientId].workCalendar.push(entry);
    grouped[clientId].analytics.total++;
    if (entry.status === 'completed') grouped[clientId].analytics.completed++;
    if (entry.isOverdue) grouped[clientId].analytics.overdue++;
  });
  
  return grouped;
};

const groupByDate = (workCalendarEntries, workItems) => {
  const grouped = {};
  
  workCalendarEntries.forEach(entry => {
    const date = moment(entry.startDate).format('YYYY-MM-DD');
    
    if (!grouped[date]) {
      grouped[date] = {
        date,
        workCalendar: [],
        workItems: [],
        analytics: { total: 0, completed: 0, overdue: 0 }
      };
    }
    
    grouped[date].workCalendar.push(entry);
    grouped[date].analytics.total++;
    if (entry.status === 'completed') grouped[date].analytics.completed++;
    if (entry.isOverdue) grouped[date].analytics.overdue++;
  });
  
  return grouped;
};

/**
 * Get filter options for frontend dropdowns
 */
const getFilterOptions = async () => {
  const [departments, projects, clients, employees] = await Promise.all([
    Department.find({}).select('name').lean(),
    Project.find({}).select('name client').populate('client', 'name').lean(),
    Client.find({}).select('name').lean(),
    User.find({ role: { $in: ['employee', 'hod'] } }).select('name email department').populate('department', 'name').lean()
  ]);

  return {
    departments,
    projects,
    clients,
    employees,
    workTypes: [
      'work-item', 'project-milestone', 'meeting', 'deadline', 
      'review', 'presentation', 'training', 'client-call', 
      'internal-task', 'other'
    ],
    statuses: ['scheduled', 'in-progress', 'completed', 'cancelled', 'postponed', 'overdue'],
    priorities: ['low', 'medium', 'high', 'urgent']
  };
};

/**
 * Utility functions for colors and calculations
 */
const getStatusColor = (status) => {
  const colors = {
    'scheduled': '#6c757d',
    'in-progress': '#0d6efd',
    'completed': '#198754',
    'cancelled': '#dc3545',
    'postponed': '#fd7e14',
    'overdue': '#dc3545'
  };
  return colors[status] || '#6c757d';
};

const getPriorityColor = (priority) => {
  const colors = {
    'low': '#28a745',
    'medium': '#ffc107',
    'high': '#fd7e14',
    'urgent': '#dc3545'
  };
  return colors[priority] || '#6c757d';
};

const calculateAverageEfficiency = (entries) => {
  const entriesWithEfficiency = entries.filter(e => e.efficiencyScore !== null);
  if (entriesWithEfficiency.length === 0) return null;
  
  const sum = entriesWithEfficiency.reduce((acc, e) => acc + e.efficiencyScore, 0);
  return Math.round(sum / entriesWithEfficiency.length);
};

/**
 * Generate comprehensive PDF report
 */
const generatePDFReport = async (options) => {
  const {
    reportType,
    workCalendarEntries,
    workItems,
    filters,
    groupBy,
    includeAnalytics,
    includeCharts,
    generatedBy
  } = options;

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // Header
      doc.fontSize(20).text('Work Calendar Report', { align: 'center' });
      doc.moveDown();

      // Report metadata
      doc.fontSize(12);
      doc.text(`Generated on: ${moment().format('MMMM DD, YYYY [at] HH:mm')}`, { align: 'right' });
      doc.text(`Generated by: ${generatedBy.name} (${generatedBy.email})`, { align: 'right' });
      doc.text(`Report Type: ${reportType.charAt(0).toUpperCase() + reportType.slice(1)}`, { align: 'right' });
      doc.moveDown();

      // Filters applied
      if (Object.keys(filters).some(key => filters[key])) {
        doc.fontSize(14).text('Filters Applied:', { underline: true });
        doc.fontSize(10);
        
        if (filters.startDate && filters.endDate) {
          doc.text(`Date Range: ${moment(filters.startDate).format('MMM DD, YYYY')} - ${moment(filters.endDate).format('MMM DD, YYYY')}`);
        }
        if (filters.department) doc.text(`Department: ${filters.department}`);
        if (filters.project) doc.text(`Project: ${filters.project}`);
        if (filters.client) doc.text(`Client: ${filters.client}`);
        if (filters.employee) doc.text(`Employee: ${filters.employee}`);
        if (filters.status) doc.text(`Status: ${filters.status}`);
        if (filters.workType) doc.text(`Work Type: ${filters.workType}`);
        if (filters.priority) doc.text(`Priority: ${filters.priority}`);
        
        doc.moveDown();
      }

      // Analytics summary
      if (includeAnalytics) {
        doc.addPage();
        doc.fontSize(16).text('Analytics Summary', { underline: true });
        doc.moveDown();

        const analytics = calculateEmployeeAnalytics(workCalendarEntries, workItems);
        
        doc.fontSize(12);
        doc.text(`Total Work Entries: ${analytics.totalWork}`);
        doc.text(`Completed Work: ${analytics.completedWork} (${Math.round((analytics.completedWork / analytics.totalWork) * 100)}%)`);
        doc.text(`In Progress Work: ${analytics.inProgressWork}`);
        doc.text(`Scheduled Work: ${analytics.scheduledWork}`);
        doc.text(`Overdue Work: ${analytics.overdueWork}`);
        doc.moveDown();

        doc.text(`Total Work Items: ${analytics.totalWorkItems}`);
        doc.text(`Completed Work Items: ${analytics.completedWorkItems}`);
        doc.text(`Overdue Work Items: ${analytics.overdueWorkItems}`);
        doc.moveDown();

        doc.text(`Total Estimated Hours: ${analytics.totalEstimatedHours}`);
        doc.text(`Total Actual Hours: ${analytics.totalActualHours}`);
        if (analytics.averageEfficiency) {
          doc.text(`Average Efficiency: ${analytics.averageEfficiency}%`);
        }
        doc.moveDown();

        // Workload by priority
        doc.text('Workload by Priority:');
        doc.text(`  Urgent: ${analytics.workloadByPriority.urgent}`);
        doc.text(`  High: ${analytics.workloadByPriority.high}`);
        doc.text(`  Medium: ${analytics.workloadByPriority.medium}`);
        doc.text(`  Low: ${analytics.workloadByPriority.low}`);
        doc.moveDown();
      }

      // Work calendar entries
      if (workCalendarEntries.length > 0) {
        doc.addPage();
        doc.fontSize(16).text('Work Calendar Entries', { underline: true });
        doc.moveDown();

        workCalendarEntries.forEach((entry, index) => {
          if (index > 0 && index % 10 === 0) {
            doc.addPage();
          }

          doc.fontSize(12).text(`${index + 1}. ${entry.title}`, { continued: false });
          doc.fontSize(10);
          
          if (entry.project?.name) {
            doc.text(`Project: ${entry.project.name}`);
          }
          if (entry.assignedTo?.name) {
            doc.text(`Assigned to: ${entry.assignedTo.name}`);
          }
          if (entry.department?.name) {
            doc.text(`Department: ${entry.department.name}`);
          }
          
          doc.text(`Status: ${entry.status}`);
          doc.text(`Priority: ${entry.priority}`);
          doc.text(`Start: ${moment(entry.startDate).format('MMM DD, YYYY HH:mm')}`);
          doc.text(`End: ${moment(entry.endDate).format('MMM DD, YYYY HH:mm')}`);
          
          if (entry.dueDate) {
            doc.text(`Due: ${moment(entry.dueDate).format('MMM DD, YYYY')}`);
          }
          
          if (entry.description) {
            doc.text(`Description: ${entry.description.substring(0, 100)}${entry.description.length > 100 ? '...' : ''}`);
          }
          
          doc.moveDown(0.5);
        });
      }

      // Work items
      if (workItems.length > 0) {
        doc.addPage();
        doc.fontSize(16).text('Work Items', { underline: true });
        doc.moveDown();

        workItems.forEach((item, index) => {
          if (index > 0 && index % 15 === 0) {
            doc.addPage();
          }

          doc.fontSize(12).text(`${index + 1}. ${item.title}`, { continued: false });
          doc.fontSize(10);
          
          if (item.project?.name) {
            doc.text(`Project: ${item.project.name}`);
          }
          if (item.assignedTo?.name) {
            doc.text(`Assigned to: ${item.assignedTo.name}`);
          }
          
          doc.text(`Type: ${item.type}`);
          doc.text(`Status: ${item.status}`);
          doc.text(`Priority: ${item.priority}`);
          doc.text(`Due: ${moment(item.dueDate).format('MMM DD, YYYY')}`);
          
          if (item.completedAt) {
            doc.text(`Completed: ${moment(item.completedAt).format('MMM DD, YYYY')}`);
          }
          
          if (item.description) {
            doc.text(`Description: ${item.description.substring(0, 80)}${item.description.length > 80 ? '...' : ''}`);
          }
          
          doc.moveDown(0.3);
        });
      }

      // Footer
      doc.fontSize(8).text(
        `Report generated by CRM Work Calendar System - ${moment().format('YYYY-MM-DD HH:mm:ss')}`,
        50,
        doc.page.height - 50,
        { align: 'center' }
      );

      doc.end();

    } catch (error) {
      reject(error);
    }
  });
};

// ============================================
// SYNC AND MAINTENANCE FUNCTIONS
// ============================================

/**
 * Sync work items to work calendar
 * Creates calendar entries for work items that don't have them
 */
export const syncWorkItemsToCalendar = async (req, res) => {
  try {
    // Only admin can trigger sync
    if (!['admin', 'superadmin'].includes(req.user.role)) {
      return res.status(403).json({
        success: false,
        message: 'Access denied. Admin privileges required.'
      });
    }

    const { projectId, employeeId, departmentId } = req.query;

    // Build query for work items to sync
    const workItemQuery = {};
    if (projectId) workItemQuery.project = projectId;
    if (employeeId) workItemQuery.assignedTo = employeeId;
    if (departmentId) {
      const deptProjects = await Project.find({ departments: departmentId }).select('_id');
      workItemQuery.project = { $in: deptProjects.map(p => p._id) };
    }

    const workItems = await WorkItem.find(workItemQuery)
      .populate('project', 'name client departments')
      .populate('assignedTo', 'name email');

    let syncedCount = 0;
    let skippedCount = 0;

    for (const workItem of workItems) {
      const existing = await WorkCalendar.findOne({
        sourceId: workItem._id,
        sourceModel: 'WorkItem'
      });

      if (!existing) {
        const calendarEntry = await createWorkCalendarEntry(workItem);
        if (calendarEntry) {
          syncedCount++;
        }
      } else {
        skippedCount++;
      }
    }

    res.status(200).json({
      success: true,
      message: `Sync completed. ${syncedCount} entries created, ${skippedCount} already existed.`,
      data: {
        syncedCount,
        skippedCount,
        totalProcessed: workItems.length
      }
    });

  } catch (error) {
    logger.error('Error in syncWorkItemsToCalendar:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to sync work items to calendar',
      error: error.message
    });
  }
};

/**
 * Update work calendar entry
 */
export const updateWorkCalendarEntry = async (req, res) => {
  try {
    const { id } = req.params;
    const updates = req.body;

    const entry = await WorkCalendar.findById(id);
    if (!entry) {
      return res.status(404).json({
        success: false,
        message: 'Work calendar entry not found'
      });
    }

    // Permission check
    if (req.user.role === 'employee' && entry.assignedTo.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'You can only update your own work calendar entries'
      });
    }

    // Update entry
    Object.keys(updates).forEach(key => {
      if (updates[key] !== undefined) {
        entry[key] = updates[key];
      }
    });

    entry.lastModifiedBy = req.user.id;
    await entry.save();

    const updatedEntry = await WorkCalendar.findById(id)
      .populate('project', 'name client')
      .populate('assignedTo', 'name email')
      .populate('department', 'name');

    res.status(200).json({
      success: true,
      message: 'Work calendar entry updated successfully',
      data: updatedEntry
    });

  } catch (error) {
    logger.error('Error in updateWorkCalendarEntry:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to update work calendar entry',
      error: error.message
    });
  }
};

/**
 * Delete work calendar entry
 */
export const deleteWorkCalendarEntry = async (req, res) => {
  try {
    const { id } = req.params;

    const entry = await WorkCalendar.findById(id);
    if (!entry) {
      return res.status(404).json({
        success: false,
        message: 'Work calendar entry not found'
      });
    }

    // Permission check
    if (req.user.role === 'employee' && entry.assignedTo.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'You can only delete your own work calendar entries'
      });
    }

    // Don't allow deletion of auto-generated entries
    if (entry.isAutoGenerated) {
      return res.status(400).json({
        success: false,
        message: 'Cannot delete auto-generated calendar entries. Update the source work item instead.'
      });
    }

    await WorkCalendar.findByIdAndDelete(id);

    res.status(200).json({
      success: true,
      message: 'Work calendar entry deleted successfully'
    });

  } catch (error) {
    logger.error('Error in deleteWorkCalendarEntry:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to delete work calendar entry',
      error: error.message
    });
  }
};

/**
 * Sync current user's work items to calendar
 */
export const syncMyWorkItemsToCalendar = async (req, res) => {
  try {
    const employeeId = req.user.id;
    
    // Use both console.log and logger to ensure we see the output
    const logMessage = `[SYNC] Starting work item sync for employee: ${employeeId}`;
    console.log(logMessage);
    logger.info(logMessage);
    
    // Also log to stderr to make sure it appears
    console.error(`[SYNC DEBUG] Employee ID: ${employeeId}, User: ${req.user.email}`);

    // Get all work items for current user
    const workItems = await WorkItem.find({ assignedTo: employeeId })
      .populate('project', 'name client departments department')
      .populate('assignedTo', 'name email');

    const foundMessage = `[SYNC] Found ${workItems.length} work items for employee: ${employeeId}`;
    console.log(foundMessage);
    console.error(foundMessage); // Also log to stderr
    logger.info(foundMessage);
    
    if (workItems.length > 0) {
      const workItemsInfo = workItems.map(item => ({ 
        id: item._id, 
        title: item.title, 
        project: item.project?.name,
        dueDate: item.dueDate 
      }));
      console.error(`[SYNC] Work items details:`, JSON.stringify(workItemsInfo, null, 2));
    } else {
      console.error(`[SYNC] No work items found for employee ${employeeId}`);
    }

    let syncedCount = 0;
    let skippedCount = 0;
    let errorCount = 0;
    const errors = [];

    for (const workItem of workItems) {
      try {
        const existing = await WorkCalendar.findOne({
          sourceId: workItem._id,
          sourceModel: 'WorkItem'
        });

        if (!existing) {
          const calendarEntry = await createWorkCalendarEntry(workItem);
          if (calendarEntry) {
            syncedCount++;
            logger.info(`Synced work item: ${workItem.title}`);
          } else {
            errorCount++;
            errors.push(`Failed to create calendar entry for: ${workItem.title}`);
          }
        } else {
          skippedCount++;
          logger.debug(`Skipped existing work item: ${workItem.title}`);
        }
      } catch (itemError) {
        errorCount++;
        errors.push(`Error processing ${workItem.title}: ${itemError.message}`);
        logger.error(`Error processing work item ${workItem._id}:`, itemError);
      }
    }

    const message = `Sync completed. ${syncedCount} entries created, ${skippedCount} already existed${errorCount > 0 ? `, ${errorCount} errors` : ''}.`;
    
    res.status(200).json({
      success: true,
      message,
      data: {
        syncedCount,
        skippedCount,
        errorCount,
        totalProcessed: workItems.length,
        errors: errors.length > 0 ? errors : undefined
      }
    });

  } catch (error) {
    logger.error('Error in syncMyWorkItemsToCalendar:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to sync your work items to calendar',
      error: error.message
    });
  }
};

/**
 * Create manual work calendar entry (API endpoint)
 */
export const createWorkCalendarEntryAPI = async (req, res) => {
  try {
    const {
      title,
      description,
      workType,
      assignedTo,
      department,
      project,
      client,
      startDate,
      endDate,
      dueDate,
      priority,
      isAllDay,
      location,
      meetingUrl,
      tags
    } = req.body;

    // Validation
    if (!title || !assignedTo || !department || !startDate || !endDate) {
      return res.status(400).json({
        success: false,
        message: 'Title, assignedTo, department, startDate, and endDate are required'
      });
    }

    // Permission check
    if (req.user.role === 'employee' && assignedTo !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Employees can only create calendar entries for themselves'
      });
    }

    const calendarEntry = new WorkCalendar({
      title,
      description,
      workType: workType || 'other',
      assignedTo,
      department,
      project,
      client,
      startDate: new Date(startDate),
      endDate: new Date(endDate),
      dueDate: dueDate ? new Date(dueDate) : null,
      priority: priority || 'medium',
      isAllDay: isAllDay || false,
      location,
      meetingUrl,
      tags: tags || [],
      status: 'scheduled',
      isAutoGenerated: false,
      createdBy: req.user.id
    });

    await calendarEntry.save();

    const populatedEntry = await WorkCalendar.findById(calendarEntry._id)
      .populate('project', 'name client')
      .populate('assignedTo', 'name email')
      .populate('department', 'name')
      .populate('client', 'name');

    res.status(201).json({
      success: true,
      message: 'Work calendar entry created successfully',
      data: populatedEntry
    });

  } catch (error) {
    logger.error('Error in createWorkCalendarEntry:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to create work calendar entry',
      error: error.message
    });
  }
};