import { Card, Badge, ProgressBar, Button } from 'react-bootstrap';
import { FaUsers, FaTasks, FaCheckCircle, FaEye, FaEdit } from 'react-icons/fa';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

/**
 * ProjectCard Component
 * Displays project information in card format with statistics
 */
const ProjectCard = ({ project, onEdit }) => {
  const navigate = useNavigate();
  const { user } = useAuth();

  // Guard against undefined project
  if (!project) {
    return null;
  }

  const getStatusColor = (status) => {
    const colors = {
      Active: 'success',
      'On Hold': 'warning',
      Completed: 'info',
      Cancelled: 'danger'
    };
    return colors[status] || 'secondary';
  };

  const handleViewProject = () => {
    navigate(`/projects/${project._id}`);
  };

  // Check if this is an incomplete auto-generated project
  const isAutoGeneratedIncomplete = () => {
    if (!project?.name || !project?.client) return false;
    
    const isAutoGenerated = project.name.includes(' Project') && project.client;
    if (!isAutoGenerated) return false;
    
    const hasMinimalDescription = !project.description || 
      project.description === `Project for ${project.client?.name}` ||
      project.description === `Project for ${project.client?.name} (${project.client?.company})` ||
      project.description.length < 20;
    
    // Only mark as incomplete if it has minimal description AND no services
    const isIncomplete = hasMinimalDescription && 
      (!project.services || project.services.length === 0);
    
    return isIncomplete;
  };

  const isIncomplete = isAutoGeneratedIncomplete();

  return (
    <Card
      className={`h-100 shadow-sm ${isIncomplete ? 'border-warning' : ''}`}
      style={{ cursor: 'pointer', transition: 'all 0.2s' }}
      onMouseEnter={(e) => {
        e.currentTarget.style.transform = 'translateY(-4px)';
        e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.15)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.transform = 'translateY(0)';
        e.currentTarget.style.boxShadow = '';
      }}
      onClick={handleViewProject}
    >
      {isIncomplete && (
        <Card.Header className="bg-warning bg-opacity-10 py-2">
          <small className="text-warning fw-bold">
            <i className="fas fa-exclamation-triangle me-1"></i>
            Needs Details
          </small>
        </Card.Header>
      )}
      <Card.Body>
        {/* Header */}
        <div className="d-flex justify-content-between align-items-start mb-3">
          <div className="flex-grow-1">
            <h5 className="mb-1">
              {project.name || 'Untitled Project'}
              {project.name?.includes(' Project') && project.client && (
                <Badge 
                  bg={isIncomplete ? "warning" : "info"} 
                  className="ms-2" 
                  style={{ fontSize: '0.7rem' }}
                >
                  {isIncomplete ? "Needs Details" : "Auto-created"}
                </Badge>
              )}
            </h5>
            {project.client && (
              <small className="text-muted">{project.client.name}</small>
            )}
          </div>
          <Badge bg={getStatusColor(project.status)}>{project.status || 'Pending'}</Badge>
        </div>

        {/* Description */}
        {project.description && (
          <p className="text-muted small mb-3" style={{ 
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            display: '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical'
          }}>
            {project.description}
          </p>
        )}

        {/* Progress */}
        <div className="mb-3">
          <div className="d-flex justify-content-between align-items-center mb-1">
            <small className="text-muted">Progress</small>
            <small className="fw-bold">{project.progress || 0}%</small>
          </div>
          <ProgressBar
            now={project.progress || 0}
            variant={
              project.progress >= 75 ? 'success' :
              project.progress >= 50 ? 'info' :
              project.progress >= 25 ? 'warning' : 'danger'
            }
            style={{ height: '6px' }}
          />
        </div>

        {/* Statistics */}
        <div className="d-flex justify-content-between text-muted small mb-3">
          <div className="d-flex align-items-center">
            <FaUsers className="me-1" />
            <span>{project.teamMembers?.length || 0} members</span>
          </div>
          <div className="d-flex align-items-center">
            <FaTasks className="me-1" />
            <span>{project.totalWorkItems || 0} items</span>
          </div>
          <div className="d-flex align-items-center">
            <FaCheckCircle className="me-1" />
            <span>{project.completedWorkItems || 0} done</span>
          </div>
        </div>

        {/* Footer */}
        <div className="d-flex justify-content-between align-items-center pt-2 border-top">
          <small className="text-muted">
            {project.projectHead?.name || 'No project head'}
          </small>
          <div className="d-flex gap-2">
            {['admin', 'superadmin', 'hr', 'manager', 'hod'].includes(user?.role) && (
              <Button
                variant="outline-secondary"
                size="sm"
                onClick={(e) => {
                  e.stopPropagation();
                  if (onEdit) onEdit(project);
                }}
                title="Edit Project"
              >
                <FaEdit />
              </Button>
            )}
            <Button
              variant="outline-primary"
              size="sm"
              onClick={(e) => {
                e.stopPropagation();
                handleViewProject();
              }}
              title="View Details"
            >
              <FaEye />
            </Button>
          </div>
        </div>
      </Card.Body>
    </Card>
  );
};

export default ProjectCard;
