import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Card, Button, Badge, Dropdown, Spinner, Form, Modal } from 'react-bootstrap';
import { Calendar, momentLocalizer } from 'react-big-calendar';
import moment from 'moment';
import { toast } from 'react-toastify';
import { useAuth } from '../../context/AuthContext';
import workCalendarApi from '../../api/workCalendarApi';
import ProfessionalWorkCreationModal from '../work/ProfessionalWorkCreationModal';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import './EmployeeWorkCalendar.css';
import './MultiEventCalendar.css';

const localizer = momentLocalizer(moment);

/**
 * Employee Work Calendar Component
 * Shows personal work calendar with filtering and different views
 */
const EmployeeWorkCalendar = ({ employeeId }) => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [calendarData, setCalendarData] = useState(null);
  const [currentView, setCurrentView] = useState('calendar');
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [showEventModal, setShowEventModal] = useState(false);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedDateForCreate, setSelectedDateForCreate] = useState(null);
  const [filters, setFilters] = useState({
    status: 'all',
    workType: 'all',
    project: 'all',
    priority: 'all',
    view: 'calendar'
  });

  const currentEmployeeId = employeeId || user?.id || user?._id;

  useEffect(() => {
    if (currentEmployeeId) {
      loadEmployeeWorkCalendar();
    } else {
      setLoading(false);
    }
  }, [currentEmployeeId, selectedDate, filters.status, filters.workType, filters.priority]);

  const loadEmployeeWorkCalendar = async () => {
    try {
      setLoading(true);
      
      // Calculate date range based on current view
      const startDate = moment(selectedDate).startOf('month').subtract(1, 'week').toDate();
      const endDate = moment(selectedDate).endOf('month').add(1, 'week').toDate();

      const response = await workCalendarApi.getEmployeeWorkCalendar(currentEmployeeId, {
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        ...filters
      });
      
      // Fix: Extract the actual data from the nested structure
      const actualData = response.data.data || response.data;
      
      setCalendarData(actualData);
    } catch (error) {
      console.error('❌ Error loading employee work calendar:', error);
      toast.error(`Failed to load work calendar: ${error.response?.data?.message || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleViewChange = (view) => {
    setCurrentView(view);
    setFilters(prev => ({ ...prev, view }));
  };

  const handleEventSelect = (event) => {
    setSelectedEvent(event.resource);
    setShowEventModal(true);
  };

  const handleFilterChange = (filterType, value) => {
    setFilters(prev => ({
      ...prev,
      [filterType]: value,
    }));
  };

  const handleDateNavigate = (date) => {
    setSelectedDate(date);
  };

  // Transform work calendar entries for calendar display
  const getCalendarEvents = () => {
    if (!calendarData?.workCalendar) {
      return [];
    }
    
    const events = calendarData.workCalendar.map(entry => {
      // Check if this is already formatted by backend or needs transformation
      const isPreFormatted = entry.start && entry.end && entry.id;
      
      if (isPreFormatted) {
        // Backend already formatted the event - use as is
        return {
          id: entry.id,
          title: entry.title,
          start: new Date(entry.start),
          end: new Date(entry.end),
          allDay: entry.allDay || false,
          resource: entry.resource || entry,
        };
      } else {
        // Transform raw work calendar entry
        const sourceIndicator = entry.isAutoGenerated && entry.sourceModel === 'WorkItem' ? '📋 ' : '📅 ';
        const projectInfo = entry.project?.name ? ` (${entry.project.name})` : '';
        const timeInfo = entry.timeTracking?.estimatedHours ? ` [${entry.timeTracking.estimatedHours}h]` : '';
        
        // For work items, check if this should be an all-day event
        const isWorkItem = entry.isAutoGenerated && entry.sourceModel === 'WorkItem';
        const shouldBeAllDay = isWorkItem || entry.isAllDay;
        
        let startDate, endDate;
        
        if (shouldBeAllDay && isWorkItem) {
          // For work items, use the due date as an all-day event
          const dueDate = new Date(entry.dueDate);
          startDate = new Date(dueDate.getFullYear(), dueDate.getMonth(), dueDate.getDate());
          endDate = new Date(dueDate.getFullYear(), dueDate.getMonth(), dueDate.getDate() + 1);
        } else {
          startDate = new Date(entry.startDate);
          endDate = new Date(entry.endDate);
        }
        
        const event = {
          id: entry._id,
          title: `${sourceIndicator}${entry.title}${projectInfo}${timeInfo}`,
          start: startDate,
          end: endDate,
          allDay: shouldBeAllDay,
          resource: entry,
        };
        
        return event;
      }
    });

    return events;
  };

  // Get status color
  const getStatusColor = (status) => {
    const colors = {
      'scheduled': '#6c757d',
      'in-progress': '#0d6efd',
      'completed': '#198754',
      'cancelled': '#dc3545',
      'postponed': '#fd7e14',
      'overdue': '#dc3545'
    };
    return colors[status] || '#6c757d';
  };

  // Get priority color
  const getPriorityColor = (priority) => {
    const colors = {
      'low': '#28a745',
      'medium': '#ffc107',
      'high': '#fd7e14',
      'urgent': '#dc3545'
    };
    return colors[priority] || '#6c757d';
  };

  // Event style getter for calendar
  const eventStyleGetter = (event) => {
    const resource = event.resource;
    const backgroundColor = getStatusColor(resource.status);
    const borderColor = getPriorityColor(resource.priority);
    
    // Build CSS classes for enhanced styling
    const cssClasses = [
      `priority-${resource.priority}`,
      `status-${resource.status}`,
      `work-type-${resource.workType}`,
      resource.isRemote ? 'remote-work' : '',
    ].filter(Boolean).join(' ');
    
    return {
      style: {
        backgroundColor,
        borderColor,
        borderWidth: '2px',
        borderStyle: 'solid',
        borderRadius: '4px',
        opacity: resource.status === 'completed' ? 0.7 : 1,
        color: 'white',
        display: 'block',
        fontSize: '12px',
        fontWeight: '500',
      },
      className: cssClasses,
    };
  };

  const handleCreateWork = (selectedDate = null) => {
    setSelectedDateForCreate(selectedDate || new Date());
    setShowCreateModal(true);
  };

  const handleSlotSelect = (slotInfo) => {
    // When user clicks on a calendar slot, open create modal with that date
    handleCreateWork(slotInfo.start);
  };

  const handleSyncWorkItems = async () => {
    try {
      setLoading(true);
      const response = await workCalendarApi.syncMyWorkItemsToCalendar();
      
      if (response.data.syncedCount > 0) {
        toast.success(`✅ Synced ${response.data.syncedCount} new work items to calendar!`);
      } else if (response.data.skippedCount > 0) {
        toast.info(`📅 All work items are already synced (${response.data.skippedCount} items up to date)`);
      } else {
        toast.info('📋 No work items found to sync');
      }
      
      loadEmployeeWorkCalendar();
    } catch (error) {
      console.error('Error syncing work items:', error);
      toast.error('Failed to sync work items');
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateWorkStatus = async (entryId, newStatus) => {
    try {
      await workCalendarApi.updateWorkCalendarEntry(entryId, { status: newStatus });
      toast.success('Work status updated successfully');
      loadEmployeeWorkCalendar();
      setShowEventModal(false);
    } catch (error) {
      console.error('Error updating work status:', error);
      toast.error('Failed to update work status');
    }
  };

  // Debug info
  if (!user) {
    return (
      <div className="text-center py-5">
        <div className="alert alert-warning">
          <strong>⚠️ Authentication Issue:</strong> No user context available. Please refresh the page or log in again.
        </div>
      </div>
    );
  }

  if (!currentEmployeeId) {
    return (
      <div className="text-center py-5">
        <div className="alert alert-warning">
          <strong>⚠️ User ID Issue:</strong> No employee ID available. 
          <br />User: {user?.name} ({user?.role})
          <br />User ID: {user?.id || user?._id}
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="text-center py-5">
        <Spinner animation="border" role="status">
          <span className="visually-hidden">Loading...</span>
        </Spinner>
        <div className="mt-3">
          <small className="text-muted">
            Loading calendar for: {user?.name} (ID: {currentEmployeeId})
          </small>
        </div>
      </div>
    );
  }

  if (!calendarData) {
    return (
      <div className="text-center py-5">
        <div className="alert alert-info">
          <strong>📅 No Calendar Data:</strong> No work calendar data available for {user?.name}.
          <br />
          <Button 
            variant="primary" 
            className="mt-2"
            onClick={loadEmployeeWorkCalendar}
          >
            Try Loading Again
          </Button>
        </div>
      </div>
    );
  }

  return (
    <Container fluid className="employee-work-calendar">
      {/* Header */}
      <Row className="mb-4">
        <Col>
          <div className="d-flex justify-content-between align-items-center">
            <div>
              <h2>
                {currentEmployeeId === (user?.id || user?._id) ? 'My Work Calendar' : `${calendarData.employee?.name}'s Work Calendar`}
              </h2>
              <p className="text-muted mb-0">
                {calendarData?.analytics?.totalWork || 0} total work entries • 
                {calendarData?.analytics?.completedWork || 0} completed • 
                {calendarData?.analytics?.overdueWork || 0} overdue
              </p>
              {currentEmployeeId === (user?.id || user?._id) && (
                <div className="mt-1">
                  <small className="text-info d-block">
                    📅 Your work items from "My Work" are automatically synced to this calendar
                  </small>
                  <small className="text-muted">
                    📋 = Work Item • 📅 = Manual Entry
                  </small>
                </div>
              )}
            </div>
            
            {/* View Controls */}
            <div className="d-flex gap-2">
              <Dropdown>
                <Dropdown.Toggle variant="outline-primary" size="sm">
                  View: {currentView}
                </Dropdown.Toggle>
                <Dropdown.Menu>
                  <Dropdown.Item onClick={() => handleViewChange('calendar')}>
                    Calendar
                  </Dropdown.Item>
                  <Dropdown.Item onClick={() => handleViewChange('timeline')}>
                    Timeline
                  </Dropdown.Item>
                  <Dropdown.Item onClick={() => handleViewChange('list')}>
                    List
                  </Dropdown.Item>
                </Dropdown.Menu>
              </Dropdown>
              
              {currentEmployeeId === (user?.id || user?._id) && (
                <>
                  <Button 
                    variant="success" 
                    size="sm"
                    onClick={handleCreateWork}
                  >
                    Add Work
                  </Button>
                  <Button 
                    variant="outline-info" 
                    size="sm"
                    onClick={handleSyncWorkItems}
                  >
                    Sync My Work
                  </Button>
                </>
              )}
              
              <Button 
                variant="outline-success" 
                size="sm"
                onClick={() => {
                  setSelectedDate(new Date());
                  loadEmployeeWorkCalendar();
                }}
              >
                Today
              </Button>
              <Button 
                variant="primary" 
                size="sm"
                onClick={loadEmployeeWorkCalendar}
              >
                Refresh
              </Button>

            </div>
          </div>
        </Col>
      </Row>

      {/* Integration Status */}
      {currentEmployeeId === (user?.id || user?._id) && (
        <Row className="mb-3">
          <Col>
            <div className={`alert py-2 mb-0 ${calendarData ? 'alert-info' : 'alert-warning'}`}>
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <strong>📋 My Work Integration:</strong> 
                  <span className="ms-2">
                    {calendarData ? (
                      <>
                        {calendarData.workItems?.length || 0} work items • 
                        {calendarData.workCalendar?.filter(entry => entry.isAutoGenerated)?.length || 0} synced to calendar
                      </>
                    ) : (
                      'Loading integration status...'
                    )}
                  </span>
                </div>
                <div className="d-flex gap-2">
                  <Button 
                    variant="outline-info" 
                    size="sm"
                    onClick={handleSyncWorkItems}
                    disabled={loading}
                  >
                    {loading ? 'Syncing...' : 'Sync Now'}
                  </Button>
                  <Button 
                    variant="outline-secondary" 
                    size="sm"
                    onClick={() => window.open('/my-work', '_blank')}
                  >
                    View My Work
                  </Button>
                </div>
              </div>
            </div>
          </Col>
        </Row>
      )}

      {/* Filters */}
      <Row className="mb-3">
        <Col>
          <Card className="border-0 shadow-sm" style={{ overflow: 'visible' }}>
            <Card.Body className="py-2" style={{ overflow: 'visible' }}>
              <div className="d-flex gap-3 align-items-center flex-wrap" style={{ overflow: 'visible' }}>
                <small className="text-muted fw-bold">Filters:</small>
                
                {/* Status Filter */}
                <Dropdown size="sm" drop="down" autoClose={true}>
                  <Dropdown.Toggle variant="outline-secondary" size="sm" id="status-dropdown">
                    Status: {filters.status}
                  </Dropdown.Toggle>
                  <Dropdown.Menu style={{ zIndex: 9999 }}>
                    <Dropdown.Item onClick={() => handleFilterChange('status', 'all')}>
                      All Status
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('status', 'scheduled')}>
                      Scheduled
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('status', 'in-progress')}>
                      In Progress
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('status', 'completed')}>
                      Completed
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('status', 'overdue')}>
                      Overdue
                    </Dropdown.Item>
                  </Dropdown.Menu>
                </Dropdown>

                {/* Work Type Filter */}
                <Dropdown size="sm" drop="down" autoClose={true}>
                  <Dropdown.Toggle variant="outline-secondary" size="sm" id="worktype-dropdown">
                    Type: {filters.workType}
                  </Dropdown.Toggle>
                  <Dropdown.Menu style={{ zIndex: 9999 }}>
                    <Dropdown.Item onClick={() => handleFilterChange('workType', 'all')}>
                      All Types
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('workType', 'work-item')}>
                      Work Items
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('workType', 'meeting')}>
                      Meetings
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('workType', 'deadline')}>
                      Deadlines
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('workType', 'review')}>
                      Reviews
                    </Dropdown.Item>
                  </Dropdown.Menu>
                </Dropdown>

                {/* Priority Filter */}
                <Dropdown size="sm" drop="down" autoClose={true}>
                  <Dropdown.Toggle variant="outline-secondary" size="sm" id="priority-dropdown">
                    Priority: {filters.priority}
                  </Dropdown.Toggle>
                  <Dropdown.Menu style={{ zIndex: 9999 }}>
                    <Dropdown.Item onClick={() => handleFilterChange('priority', 'all')}>
                      All Priorities
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('priority', 'urgent')}>
                      Urgent
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('priority', 'high')}>
                      High
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('priority', 'medium')}>
                      Medium
                    </Dropdown.Item>
                    <Dropdown.Item onClick={() => handleFilterChange('priority', 'low')}>
                      Low
                    </Dropdown.Item>
                  </Dropdown.Menu>
                </Dropdown>
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      <Row>
        {/* Main Calendar View */}
        <Col lg={9}>
          <Card className="border-0 shadow-sm">
            <Card.Body>
              {currentView === 'calendar' && (
                <div>
                  <Calendar
                    localizer={localizer}
                    events={getCalendarEvents()}
                    startAccessor="start"
                    endAccessor="end"
                    style={{ height: 580 }}
                    onSelectEvent={handleEventSelect}
                    onSelectSlot={handleSlotSelect}
                    onNavigate={handleDateNavigate}
                    eventPropGetter={eventStyleGetter}
                    views={['month', 'week', 'day', 'agenda']}
                    defaultView="month"
                    date={selectedDate}
                    popup
                    selectable
                    showMultiDayTimes
                    step={30}
                    timeslots={2}
                  />
                </div>
              )}

              {currentView === 'timeline' && (
                <div className="timeline-view">
                  <h5 className="mb-3">Work Timeline</h5>
                  {calendarData.workCalendar
                    ?.sort((a, b) => new Date(a.startDate) - new Date(b.startDate))
                    .map(work => (
                    <div key={work._id} className="timeline-item mb-3 p-3 border rounded">
                      <div className="d-flex justify-content-between align-items-start">
                        <div className="flex-grow-1">
                          <h6 className="mb-1">{work.title}</h6>
                          <p className="text-muted small mb-2">{work.description}</p>
                          <div className="d-flex gap-2 mb-2">
                            <Badge bg={work.status === 'completed' ? 'success' : 
                                      work.status === 'in-progress' ? 'primary' : 
                                      work.status === 'overdue' ? 'danger' : 'secondary'}>
                              {work.status}
                            </Badge>
                            <Badge bg={work.priority === 'urgent' ? 'danger' : 
                                      work.priority === 'high' ? 'warning' : 
                                      work.priority === 'medium' ? 'info' : 'light'}>
                              {work.priority}
                            </Badge>
                            <Badge bg="light" text="dark">{work.workType}</Badge>
                          </div>
                          <small className="text-muted">
                            {moment(work.startDate).format('MMM DD, YYYY HH:mm')} - 
                            {moment(work.endDate).format('MMM DD, YYYY HH:mm')}
                          </small>
                        </div>
                        <div className="text-end">
                          {work.project && (
                            <div className="small text-muted mb-1">
                              Project: {work.project.name}
                            </div>
                          )}
                          <Button
                            size="sm"
                            variant="outline-primary"
                            onClick={() => handleEventSelect({ resource: work })}
                          >
                            View Details
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {currentView === 'list' && (
                <div className="list-view">
                  <h5 className="mb-3">Work List</h5>
                  <div className="table-responsive">
                    <table className="table table-hover">
                      <thead>
                        <tr>
                          <th>Title</th>
                          <th>Project</th>
                          <th>Status</th>
                          <th>Priority</th>
                          <th>Due Date</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {calendarData.workCalendar?.map(work => (
                          <tr key={work._id}>
                            <td>
                              <div>
                                <strong>{work.title}</strong>
                                <div className="small text-muted">{work.workType}</div>
                              </div>
                            </td>
                            <td>{work.project?.name || 'No Project'}</td>
                            <td>
                              <Badge bg={work.status === 'completed' ? 'success' : 
                                        work.status === 'in-progress' ? 'primary' : 
                                        work.status === 'overdue' ? 'danger' : 'secondary'}>
                                {work.status}
                              </Badge>
                            </td>
                            <td>
                              <Badge bg={work.priority === 'urgent' ? 'danger' : 
                                        work.priority === 'high' ? 'warning' : 
                                        work.priority === 'medium' ? 'info' : 'light'}>
                                {work.priority}
                              </Badge>
                            </td>
                            <td>
                              {work.dueDate ? moment(work.dueDate).format('MMM DD, YYYY') : 'No due date'}
                            </td>
                            <td>
                              <Button
                                size="sm"
                                variant="outline-primary"
                                onClick={() => handleEventSelect({ resource: work })}
                              >
                                View
                              </Button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </Card.Body>
          </Card>
        </Col>

        {/* Sidebar */}
        <Col lg={3}>
          {/* Compact Analytics Card */}
          <Card className="border-0 shadow-sm" style={{ height: 'fit-content' }}>
            <Card.Header className="bg-light py-2">
              <h6 className="mb-0 small">Work Summary</h6>
            </Card.Header>
            <Card.Body className="py-2">
              {/* Status Overview */}
              <div className="mb-3">
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">Total:</small>
                  <Badge bg="primary" className="px-2">{calendarData?.analytics?.totalWork || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">Completed:</small>
                  <Badge bg="success" className="px-2">{calendarData?.analytics?.completedWork || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">In Progress:</small>
                  <Badge bg="info" className="px-2">{calendarData?.analytics?.inProgressWork || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">Overdue:</small>
                  <Badge bg="danger" className="px-2">{calendarData?.analytics?.overdueWork || 0}</Badge>
                </div>
              </div>
              
              {/* Priority Breakdown */}
              <div className="border-top pt-2 mb-3">
                <small className="text-muted fw-bold d-block mb-2">Priority Breakdown</small>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-danger">Urgent:</small>
                  <Badge bg="danger" size="sm">{calendarData?.analytics?.workloadByPriority?.urgent || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-warning">High:</small>
                  <Badge bg="warning" size="sm">{calendarData?.analytics?.workloadByPriority?.high || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-info">Medium:</small>
                  <Badge bg="info" size="sm">{calendarData?.analytics?.workloadByPriority?.medium || 0}</Badge>
                </div>
                <div className="d-flex justify-content-between align-items-center">
                  <small className="text-muted">Low:</small>
                  <Badge bg="light" text="dark" size="sm">{calendarData?.analytics?.workloadByPriority?.low || 0}</Badge>
                </div>
              </div>
              
              {/* Time Tracking */}
              <div className="border-top pt-2">
                <small className="text-muted fw-bold d-block mb-2">Time Tracking</small>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">Estimated:</small>
                  <small className="fw-bold">{calendarData?.analytics?.totalEstimatedHours || 0}h</small>
                </div>
                <div className="d-flex justify-content-between align-items-center mb-1">
                  <small className="text-muted">Actual:</small>
                  <small className="fw-bold">{calendarData?.analytics?.totalActualHours || 0}h</small>
                </div>
                {calendarData?.analytics?.averageEfficiency && (
                  <div className="d-flex justify-content-between align-items-center">
                    <small className="text-muted">Efficiency:</small>
                    <Badge 
                      bg={calendarData.analytics.averageEfficiency >= 90 ? 'success' : 
                          calendarData.analytics.averageEfficiency >= 70 ? 'warning' : 'danger'}
                      size="sm"
                    >
                      {calendarData.analytics.averageEfficiency}%
                    </Badge>
                  </div>
                )}
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      {/* Event Details Modal */}
      <Modal show={showEventModal} onHide={() => setShowEventModal(false)} size="lg">
        <Modal.Header closeButton>
          <Modal.Title>Work Details</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {selectedEvent && (
            <div>
              <h5>{selectedEvent.title}</h5>
              {selectedEvent.description && (
                <p className="text-muted">{selectedEvent.description}</p>
              )}
              
              <Row>
                <Col md={6}>
                  <strong>Status:</strong>
                  <Badge 
                    bg={selectedEvent.status === 'completed' ? 'success' : 
                        selectedEvent.status === 'in-progress' ? 'primary' : 
                        selectedEvent.status === 'overdue' ? 'danger' : 'secondary'}
                    className="ms-2"
                  >
                    {selectedEvent.status}
                  </Badge>
                </Col>
                <Col md={6}>
                  <strong>Priority:</strong>
                  <Badge 
                    bg={selectedEvent.priority === 'urgent' ? 'danger' : 
                        selectedEvent.priority === 'high' ? 'warning' : 
                        selectedEvent.priority === 'medium' ? 'info' : 'light'}
                    className="ms-2"
                  >
                    {selectedEvent.priority}
                  </Badge>
                </Col>
              </Row>
              
              <hr />
              
              <Row>
                <Col md={6}>
                  <strong>Start:</strong> {moment(selectedEvent.startDate).format('MMM DD, YYYY HH:mm')}
                </Col>
                <Col md={6}>
                  <strong>End:</strong> {moment(selectedEvent.endDate).format('MMM DD, YYYY HH:mm')}
                </Col>
              </Row>
              
              {selectedEvent.dueDate && (
                <div className="mt-2">
                  <strong>Due Date:</strong> {moment(selectedEvent.dueDate).format('MMM DD, YYYY')}
                </div>
              )}
              
              {selectedEvent.project && (
                <div className="mt-2">
                  <strong>Project:</strong> {selectedEvent.project.name}
                </div>
              )}
              
              {selectedEvent.location && (
                <div className="mt-2">
                  <strong>Location:</strong> {selectedEvent.location}
                </div>
              )}
              
              {selectedEvent.timeTracking && (
                <div className="mt-3">
                  <h6>Time Tracking</h6>
                  <div>Estimated: {selectedEvent.timeTracking.estimatedHours}h</div>
                  <div>Actual: {selectedEvent.timeTracking.actualHours}h</div>
                </div>
              )}
            </div>
          )}
        </Modal.Body>
        <Modal.Footer>
          {currentEmployeeId === (user?.id || user?._id) && selectedEvent && selectedEvent.status !== 'completed' && (
            <div className="d-flex gap-2">
              {selectedEvent.status === 'scheduled' && (
                <Button 
                  variant="primary" 
                  onClick={() => handleUpdateWorkStatus(selectedEvent._id, 'in-progress')}
                >
                  Start Work
                </Button>
              )}
              {selectedEvent.status === 'in-progress' && (
                <Button 
                  variant="success" 
                  onClick={() => handleUpdateWorkStatus(selectedEvent._id, 'completed')}
                >
                  Mark Complete
                </Button>
              )}
            </div>
          )}
          <Button variant="secondary" onClick={() => setShowEventModal(false)}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>

      {/* Professional Work Creation Modal */}
      <ProfessionalWorkCreationModal
        show={showCreateModal}
        onHide={() => setShowCreateModal(false)}
        onSuccess={loadEmployeeWorkCalendar}
        selectedDate={selectedDateForCreate}
        mode="calendar-focused"
      />
    </Container>
  );
};

export default EmployeeWorkCalendar;